language: java
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - openjdk8
before_install:
  - docker pull vimc/montagu-db:master
  - docker pull vimc/montagu-migrate:master
install:
  - npm install codecov -g
  - travis_retry sudo ./libsodium/install-libsodium.sh
  - ./src/gradlew -p src
before_script:
  - sudo mkdir -p /etc/montagu/api/ && sudo touch /etc/montagu/api/go_signal
  - ./src/gradlew -p src :startDatabase :startOrderlyWeb :startTaskQueue :startTestAPI
script:
  - ./src/gradlew -p src :testLibrary :stopTestAPI
# need to stop and re-start orderly-web on host network for blackbox tests against app running on metal
  - ./scripts/stop-orderly-web.sh host
  - ./scripts/start-orderly-web.sh host
  - nohup ./src/gradlew -p src :run > /dev/null 2>&1 &
  - ./src/gradlew -p src :blackboxTests:test
after_success:
  - ./src/gradlew -p src :app:jacocoTestReport
  - ./src/gradlew -p src :blackboxTests:jacocoTestReport
  - ./src/gradlew -p src :databaseTests:jacocoTestReport
  - ./src/gradlew -p src :security:jacocoTestReport
  - ./src/gradlew -p src :serialization:jacocoTestReport
  - ./src/gradlew -p src :userCLI:jacocoTestReport
  - codecov -f src/app/coverage/test/*.xml
  - codecov -f src/blackboxTests/coverage/test/*.xml
  - codecov -f src/databaseTests/coverage/test/*.xml
  - codecov -f src/emails/coverage/test/*.xml
  - codecov -f src/security/coverage/test/*.xml
  - codecov -f src/serialization/coverage/test/*.xml
  - codecov -f src/userCLI/coverage/test/*.xml
services:
  - docker
