version: '2'
services:
  api:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-api:${MONTAGU_API_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-db:master
