version: '2'
services:
  api:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-api:${MONTAGU_API_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - emails:/tmp/montagu_emails
  db:
    image: docker.montagu.dide.ic.ac.uk:5000/montagu-db:${MONTAGU_DB_VERSION}
    command: /etc/montagu/postgresql.test.conf
  orderly_web:
    image: vimc/orderly-web:master
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}/src/demo:/orderly
      - ${PWD}/src/config/blackboxTests/orderlyweb:/etc/orderly/web
  orderly:
    image: vimc/orderly.server:master
    user: ${ORDERLY_SERVER_USER_ID}
    command: /orderly
    ports:
      - "8321:8321"
    volumes:
      - ${PWD}/src/demo:/orderly
    logging:
      driver: none
  mq:
    image: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - mq:/var/lib/rabbitmq
  task_queue:
    image: vimc/task-queue-worker:vimc-4257
    depends_on:
      - mq
volumes:
  emails:
  mq:
