/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.api.db.tables.BurdenEstimateSet;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BurdenEstimateSetRecord extends UpdatableRecordImpl<BurdenEstimateSetRecord> implements Record10<Integer, Integer, Integer, String, String, String, Boolean, Boolean, String, Timestamp> {

    private static final long serialVersionUID = 1480674588;

    /**
     * Setter for <code>public.burden_estimate_set.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.burden_estimate_set.responsibility</code>.
     */
    public void setResponsibility(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.responsibility</code>.
     */
    public Integer getResponsibility() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.burden_estimate_set.model_version</code>.
     */
    public void setModelVersion(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.model_version</code>.
     */
    public Integer getModelVersion() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.burden_estimate_set.run_info</code>.
     */
    public void setRunInfo(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.run_info</code>.
     */
    public String getRunInfo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.burden_estimate_set.validation</code>.
     */
    public void setValidation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.validation</code>.
     */
    public String getValidation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.burden_estimate_set.comment</code>.
     */
    public void setComment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.comment</code>.
     */
    public String getComment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.burden_estimate_set.interpolated</code>.
     */
    public void setInterpolated(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.interpolated</code>.
     */
    public Boolean getInterpolated() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.burden_estimate_set.complete</code>.
     */
    public void setComplete(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.complete</code>.
     */
    public Boolean getComplete() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.burden_estimate_set.uploaded_by</code>.
     */
    public void setUploadedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.uploaded_by</code>.
     */
    public String getUploadedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.burden_estimate_set.uploaded_on</code>.
     */
    public void setUploadedOn(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set.uploaded_on</code>.
     */
    public Timestamp getUploadedOn() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, String, Boolean, Boolean, String, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, String, String, Boolean, Boolean, String, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.RESPONSIBILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.MODEL_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.RUN_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.VALIDATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.INTERPOLATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.COMPLETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.UPLOADED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return BurdenEstimateSet.BURDEN_ESTIMATE_SET.UPLOADED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getResponsibility();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModelVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRunInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getValidation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getInterpolated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getComplete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUploadedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUploadedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value2(Integer value) {
        setResponsibility(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value3(Integer value) {
        setModelVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value4(String value) {
        setRunInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value5(String value) {
        setValidation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value6(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value7(Boolean value) {
        setInterpolated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value8(Boolean value) {
        setComplete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value9(String value) {
        setUploadedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord value10(Timestamp value) {
        setUploadedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateSetRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, Boolean value7, Boolean value8, String value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BurdenEstimateSetRecord
     */
    public BurdenEstimateSetRecord() {
        super(BurdenEstimateSet.BURDEN_ESTIMATE_SET);
    }

    /**
     * Create a detached, initialised BurdenEstimateSetRecord
     */
    public BurdenEstimateSetRecord(Integer id, Integer responsibility, Integer modelVersion, String runInfo, String validation, String comment, Boolean interpolated, Boolean complete, String uploadedBy, Timestamp uploadedOn) {
        super(BurdenEstimateSet.BURDEN_ESTIMATE_SET);

        set(0, id);
        set(1, responsibility);
        set(2, modelVersion);
        set(3, runInfo);
        set(4, validation);
        set(5, comment);
        set(6, interpolated);
        set(7, complete);
        set(8, uploadedBy);
        set(9, uploadedOn);
    }
}
