/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.api.db.tables.Coverage;

import javax.annotation.Generated;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CoverageRecord extends UpdatableRecordImpl<CoverageRecord> implements Record9<Integer, Integer, Integer, String, Integer, Integer, BigDecimal, Boolean, String> {

    private static final long serialVersionUID = -525319127;

    /**
     * Setter for <code>public.coverage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.coverage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.coverage.coverage_set</code>.
     */
    public void setCoverageSet(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.coverage.coverage_set</code>.
     */
    public Integer getCoverageSet() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.coverage.year</code>.
     */
    public void setYear(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.coverage.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.coverage.country</code>.
     */
    public void setCountry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.coverage.country</code>.
     */
    public String getCountry() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.coverage.age_from</code>.
     */
    public void setAgeFrom(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.coverage.age_from</code>.
     */
    public Integer getAgeFrom() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.coverage.age_to</code>.
     */
    public void setAgeTo(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.coverage.age_to</code>.
     */
    public Integer getAgeTo() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.coverage.percentage_coverage</code>.
     */
    public void setPercentageCoverage(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.coverage.percentage_coverage</code>.
     */
    public BigDecimal getPercentageCoverage() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.coverage.gavi_support</code>.
     */
    public void setGaviSupport(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.coverage.gavi_support</code>.
     */
    public Boolean getGaviSupport() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.coverage.activity</code>.
     */
    public void setActivity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.coverage.activity</code>.
     */
    public String getActivity() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, Integer, Integer, BigDecimal, Boolean, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, Integer, Integer, BigDecimal, Boolean, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Coverage.COVERAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Coverage.COVERAGE.COVERAGE_SET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Coverage.COVERAGE.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Coverage.COVERAGE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Coverage.COVERAGE.AGE_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Coverage.COVERAGE.AGE_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Coverage.COVERAGE.PERCENTAGE_COVERAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Coverage.COVERAGE.GAVI_SUPPORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Coverage.COVERAGE.ACTIVITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCoverageSet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAgeFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getAgeTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getPercentageCoverage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getGaviSupport();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getActivity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value2(Integer value) {
        setCoverageSet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value3(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value4(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value5(Integer value) {
        setAgeFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value6(Integer value) {
        setAgeTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value7(BigDecimal value) {
        setPercentageCoverage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value8(Boolean value) {
        setGaviSupport(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord value9(String value) {
        setActivity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, BigDecimal value7, Boolean value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoverageRecord
     */
    public CoverageRecord() {
        super(Coverage.COVERAGE);
    }

    /**
     * Create a detached, initialised CoverageRecord
     */
    public CoverageRecord(Integer id, Integer coverageSet, Integer year, String country, Integer ageFrom, Integer ageTo, BigDecimal percentageCoverage, Boolean gaviSupport, String activity) {
        super(Coverage.COVERAGE);

        set(0, id);
        set(1, coverageSet);
        set(2, year);
        set(3, country);
        set(4, ageFrom);
        set(5, ageTo);
        set(6, percentageCoverage);
        set(7, gaviSupport);
        set(8, activity);
    }
}
