package uk.ac.imperial.vimc.demo.app.models

data class Country(val id: String, val name: String) {
    override fun toString(): String = id
}

object StaticCountries {
    val all = setOf(
            Country("AFG", "Afghanistan"),
            Country("ALB", "Albania"),
            Country("AGO", "Angola"),
            Country("ARM", "Armenia"),
            Country("AZE", "Azerbaijan"),
            Country("BGD", "Bangladesh"),
            Country("BLZ", "Belize"),
            Country("BEN", "Benin"),
            Country("BTN", "Bhutan"),
            Country("BOL", "Bolivia"),
            Country("BIH", "Bosnia and Herzegovina"),
            Country("BFA", "Burkina Faso"),
            Country("BDI", "Burundi"),
            Country("KHM", "Cambodia"),
            Country("CMR", "Cameroon"),
            Country("CPV", "Cape Verde"),
            Country("CAF", "Central African Republic"),
            Country("TCD", "Chad"),
            Country("CHN", "China"),
            Country("COM", "Comoros"),
            Country("COD", "Congo, DR"),
            Country("COG", "Congo, Rep"),
            Country("CIV", "Cote d'Ivoire"),
            Country("CUB", "Cuba"),
            Country("DJI", "Djibouti"),
            Country("EGY", "Egypt"),
            Country("SLV", "El Salvador"),
            Country("ERI", "Eritrea"),
            Country("ETH", "Ethiopia"),
            Country("FJI", "Fiji"),
            Country("GMB", "Gambia"),
            Country("GEO", "Georgia"),
            Country("GHA", "Ghana"),
            Country("GTM", "Guatemala"),
            Country("GIN", "Guinea"),
            Country("GNB", "Guinea-Bissau"),
            Country("GUY", "Guyana"),
            Country("HTI", "Haiti"),
            Country("HND", "Honduras"),
            Country("IND", "India"),
            Country("IDN", "Indonesia"),
            Country("IRQ", "Iraq"),
            Country("KEN", "Kenya"),
            Country("KIR", "Kiribati"),
            Country("PRK", "Korea, DPR"),
            Country("XK", "Kosovo"),
            Country("KGZ", "Kyrgyzstan"),
            Country("LAO", "Lao PDR"),
            Country("LSO", "Lesotho"),
            Country("LBR", "Liberia"),
            Country("MDG", "Madagascar"),
            Country("MWI", "Malawi"),
            Country("MLI", "Mali"),
            Country("MHL", "Marshall Islands"),
            Country("MRT", "Mauritania"),
            Country("FSM", "Micronesia"),
            Country("MDA", "Moldova"),
            Country("MNG", "Mongolia"),
            Country("MAR", "Morocco"),
            Country("MOZ", "Mozambique"),
            Country("MMR", "Myanmar"),
            Country("NPL", "Nepal"),
            Country("NIC", "Nicaragua"),
            Country("NER", "Niger"),
            Country("NGA", "Nigeria"),
            Country("PAK", "Pakistan"),
            Country("PNG", "Papua New Guinea"),
            Country("PRY", "Paraguay"),
            Country("PHL", "Philippines"),
            Country("RWA", "Rwanda"),
            Country("WSM", "Samoa"),
            Country("STP", "Sao Tome e Principe"),
            Country("SEN", "Senegal"),
            Country("SLE", "Sierra Leone"),
            Country("SLB", "Solomon Islands"),
            Country("SOM", "Somalia"),
            Country("LKA", "Sri Lanka"),
            Country("SDN", "Sudan: North"),
            Country("SSD", "Sudan: South"),
            Country("SWZ", "Swaziland"),
            Country("SYR", "Syria"),
            Country("TJK", "Tajikistan"),
            Country("TZA", "Tanzania"),
            Country("TLS", "Timor-Leste"),
            Country("TGO", "Togo"),
            Country("TON", "Tonga"),
            Country("TKM", "Turkmenistan"),
            Country("TUV", "Tuvalu"),
            Country("UGA", "Uganda"),
            Country("UKR", "Ukraine"),
            Country("UZB", "Uzbekistan"),
            Country("VUT", "Vanuatu"),
            Country("VNM", "Vietnam"),
            Country("PSE", "West Bank and Gaza"),
            Country("YEM", "Yemen"),
            Country("ZMB", "Zambia"),
            Country("ZWE", "Zimbabwe")
    )
}