/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.api.db.Keys;
import org.vaccineimpact.api.db.Public;
import org.vaccineimpact.api.db.tables.records.ScenarioTypeRecord;


/**
 * This is just "routine" or "campaign".
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScenarioType extends TableImpl<ScenarioTypeRecord> {

    private static final long serialVersionUID = 1217672350;

    /**
     * The reference instance of <code>public.scenario_type</code>
     */
    public static final ScenarioType SCENARIO_TYPE = new ScenarioType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScenarioTypeRecord> getRecordType() {
        return ScenarioTypeRecord.class;
    }

    /**
     * The column <code>public.scenario_type.id</code>.
     */
    public final TableField<ScenarioTypeRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaultValue(org.jooq.impl.DSL.field("'NULL'::text", org.jooq.impl.SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.scenario_type.name</code>.
     */
    public final TableField<ScenarioTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.field("'NULL'::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.scenario_type</code> table reference
     */
    public ScenarioType() {
        this("scenario_type", null);
    }

    /**
     * Create an aliased <code>public.scenario_type</code> table reference
     */
    public ScenarioType(String alias) {
        this(alias, SCENARIO_TYPE);
    }

    private ScenarioType(String alias, Table<ScenarioTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScenarioType(String alias, Table<ScenarioTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "This is just \"routine\" or \"campaign\".");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScenarioTypeRecord> getPrimaryKey() {
        return Keys.SCENARIO_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScenarioTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<ScenarioTypeRecord>>asList(Keys.SCENARIO_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScenarioType as(String alias) {
        return new ScenarioType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScenarioType rename(String name) {
        return new ScenarioType(name, null);
    }
}
