/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.vaccineimpact.api.db.tables.ActivityType;
import org.vaccineimpact.api.db.tables.AppUser;
import org.vaccineimpact.api.db.tables.BurdenEstimate;
import org.vaccineimpact.api.db.tables.BurdenEstimateSet;
import org.vaccineimpact.api.db.tables.Country;
import org.vaccineimpact.api.db.tables.Coverage;
import org.vaccineimpact.api.db.tables.CoverageSet;
import org.vaccineimpact.api.db.tables.Disease;
import org.vaccineimpact.api.db.tables.GaviSupportLevel;
import org.vaccineimpact.api.db.tables.Model;
import org.vaccineimpact.api.db.tables.ModelVersion;
import org.vaccineimpact.api.db.tables.ModellingGroup;
import org.vaccineimpact.api.db.tables.Outcome;
import org.vaccineimpact.api.db.tables.Permission;
import org.vaccineimpact.api.db.tables.Responsibility;
import org.vaccineimpact.api.db.tables.ResponsibilitySet;
import org.vaccineimpact.api.db.tables.ResponsibilitySetStatus;
import org.vaccineimpact.api.db.tables.Role;
import org.vaccineimpact.api.db.tables.RolePermission;
import org.vaccineimpact.api.db.tables.Scenario;
import org.vaccineimpact.api.db.tables.ScenarioCoverageSet;
import org.vaccineimpact.api.db.tables.ScenarioDescription;
import org.vaccineimpact.api.db.tables.Touchstone;
import org.vaccineimpact.api.db.tables.TouchstoneCountry;
import org.vaccineimpact.api.db.tables.TouchstoneName;
import org.vaccineimpact.api.db.tables.TouchstoneStatus;
import org.vaccineimpact.api.db.tables.UserRole;
import org.vaccineimpact.api.db.tables.Vaccine;
import org.vaccineimpact.api.db.tables.records.ActivityTypeRecord;
import org.vaccineimpact.api.db.tables.records.AppUserRecord;
import org.vaccineimpact.api.db.tables.records.BurdenEstimateRecord;
import org.vaccineimpact.api.db.tables.records.BurdenEstimateSetRecord;
import org.vaccineimpact.api.db.tables.records.CountryRecord;
import org.vaccineimpact.api.db.tables.records.CoverageRecord;
import org.vaccineimpact.api.db.tables.records.CoverageSetRecord;
import org.vaccineimpact.api.db.tables.records.DiseaseRecord;
import org.vaccineimpact.api.db.tables.records.GaviSupportLevelRecord;
import org.vaccineimpact.api.db.tables.records.ModelRecord;
import org.vaccineimpact.api.db.tables.records.ModelVersionRecord;
import org.vaccineimpact.api.db.tables.records.ModellingGroupRecord;
import org.vaccineimpact.api.db.tables.records.OutcomeRecord;
import org.vaccineimpact.api.db.tables.records.PermissionRecord;
import org.vaccineimpact.api.db.tables.records.ResponsibilityRecord;
import org.vaccineimpact.api.db.tables.records.ResponsibilitySetRecord;
import org.vaccineimpact.api.db.tables.records.ResponsibilitySetStatusRecord;
import org.vaccineimpact.api.db.tables.records.RolePermissionRecord;
import org.vaccineimpact.api.db.tables.records.RoleRecord;
import org.vaccineimpact.api.db.tables.records.ScenarioCoverageSetRecord;
import org.vaccineimpact.api.db.tables.records.ScenarioDescriptionRecord;
import org.vaccineimpact.api.db.tables.records.ScenarioRecord;
import org.vaccineimpact.api.db.tables.records.TouchstoneCountryRecord;
import org.vaccineimpact.api.db.tables.records.TouchstoneNameRecord;
import org.vaccineimpact.api.db.tables.records.TouchstoneRecord;
import org.vaccineimpact.api.db.tables.records.TouchstoneStatusRecord;
import org.vaccineimpact.api.db.tables.records.UserRoleRecord;
import org.vaccineimpact.api.db.tables.records.VaccineRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BurdenEstimateRecord, Integer> IDENTITY_BURDEN_ESTIMATE = Identities0.IDENTITY_BURDEN_ESTIMATE;
    public static final Identity<BurdenEstimateSetRecord, Integer> IDENTITY_BURDEN_ESTIMATE_SET = Identities0.IDENTITY_BURDEN_ESTIMATE_SET;
    public static final Identity<CoverageRecord, Integer> IDENTITY_COVERAGE = Identities0.IDENTITY_COVERAGE;
    public static final Identity<CoverageSetRecord, Integer> IDENTITY_COVERAGE_SET = Identities0.IDENTITY_COVERAGE_SET;
    public static final Identity<ModelVersionRecord, Integer> IDENTITY_MODEL_VERSION = Identities0.IDENTITY_MODEL_VERSION;
    public static final Identity<OutcomeRecord, Integer> IDENTITY_OUTCOME = Identities0.IDENTITY_OUTCOME;
    public static final Identity<ResponsibilityRecord, Integer> IDENTITY_RESPONSIBILITY = Identities0.IDENTITY_RESPONSIBILITY;
    public static final Identity<ResponsibilitySetRecord, Integer> IDENTITY_RESPONSIBILITY_SET = Identities0.IDENTITY_RESPONSIBILITY_SET;
    public static final Identity<RoleRecord, Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
    public static final Identity<ScenarioRecord, Integer> IDENTITY_SCENARIO = Identities0.IDENTITY_SCENARIO;
    public static final Identity<ScenarioCoverageSetRecord, Integer> IDENTITY_SCENARIO_COVERAGE_SET = Identities0.IDENTITY_SCENARIO_COVERAGE_SET;
    public static final Identity<TouchstoneCountryRecord, Integer> IDENTITY_TOUCHSTONE_COUNTRY = Identities0.IDENTITY_TOUCHSTONE_COUNTRY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActivityTypeRecord> ACTIVITY_TYPE_PKEY = UniqueKeys0.ACTIVITY_TYPE_PKEY;
    public static final UniqueKey<AppUserRecord> APP_USER_PKEY = UniqueKeys0.APP_USER_PKEY;
    public static final UniqueKey<BurdenEstimateRecord> BURDEN_ESTIMATE_PKEY = UniqueKeys0.BURDEN_ESTIMATE_PKEY;
    public static final UniqueKey<BurdenEstimateSetRecord> BURDEN_ESTIMATE_SET_PKEY = UniqueKeys0.BURDEN_ESTIMATE_SET_PKEY;
    public static final UniqueKey<CountryRecord> COUNTRY_PKEY = UniqueKeys0.COUNTRY_PKEY;
    public static final UniqueKey<CoverageRecord> COVERAGE_PKEY = UniqueKeys0.COVERAGE_PKEY;
    public static final UniqueKey<CoverageSetRecord> COVERAGE_SET_PKEY = UniqueKeys0.COVERAGE_SET_PKEY;
    public static final UniqueKey<DiseaseRecord> DISEASE_PKEY = UniqueKeys0.DISEASE_PKEY;
    public static final UniqueKey<GaviSupportLevelRecord> GAVI_SUPPORT_LEVEL_PKEY = UniqueKeys0.GAVI_SUPPORT_LEVEL_PKEY;
    public static final UniqueKey<ModelRecord> MODEL_PKEY = UniqueKeys0.MODEL_PKEY;
    public static final UniqueKey<ModelVersionRecord> MODEL_VERSION_PKEY = UniqueKeys0.MODEL_VERSION_PKEY;
    public static final UniqueKey<ModelVersionRecord> MODEL_VERSION_MODEL_VERSION_KEY = UniqueKeys0.MODEL_VERSION_MODEL_VERSION_KEY;
    public static final UniqueKey<ModellingGroupRecord> MODELLING_GROUP_PKEY = UniqueKeys0.MODELLING_GROUP_PKEY;
    public static final UniqueKey<OutcomeRecord> OUTCOME_PKEY = UniqueKeys0.OUTCOME_PKEY;
    public static final UniqueKey<OutcomeRecord> OUTCOME_CODE_KEY = UniqueKeys0.OUTCOME_CODE_KEY;
    public static final UniqueKey<PermissionRecord> PERMISSION_PKEY = UniqueKeys0.PERMISSION_PKEY;
    public static final UniqueKey<ResponsibilityRecord> RESPONSIBILITY_PKEY = UniqueKeys0.RESPONSIBILITY_PKEY;
    public static final UniqueKey<ResponsibilityRecord> RESPONSIBILITY_RESPONSIBILITY_SET_SCENARIO_KEY = UniqueKeys0.RESPONSIBILITY_RESPONSIBILITY_SET_SCENARIO_KEY;
    public static final UniqueKey<ResponsibilitySetRecord> RESPONSIBILITY_SET_PKEY = UniqueKeys0.RESPONSIBILITY_SET_PKEY;
    public static final UniqueKey<ResponsibilitySetRecord> RESPONSIBILITY_SET_MODELLING_GROUP_TOUCHSTONE_KEY = UniqueKeys0.RESPONSIBILITY_SET_MODELLING_GROUP_TOUCHSTONE_KEY;
    public static final UniqueKey<ResponsibilitySetStatusRecord> RESPONSIBILITY_SET_STATUS_PKEY = UniqueKeys0.RESPONSIBILITY_SET_STATUS_PKEY;
    public static final UniqueKey<RoleRecord> ROLE_PKEY = UniqueKeys0.ROLE_PKEY;
    public static final UniqueKey<RolePermissionRecord> ROLE_PERMISSION_PKEY = UniqueKeys0.ROLE_PERMISSION_PKEY;
    public static final UniqueKey<ScenarioRecord> SCENARIO_PKEY = UniqueKeys0.SCENARIO_PKEY;
    public static final UniqueKey<ScenarioRecord> SCENARIO_TOUCHSTONE_SCENARIO_DESCRIPTION_KEY = UniqueKeys0.SCENARIO_TOUCHSTONE_SCENARIO_DESCRIPTION_KEY;
    public static final UniqueKey<ScenarioCoverageSetRecord> SCENARIO_COVERAGE_SET_PKEY = UniqueKeys0.SCENARIO_COVERAGE_SET_PKEY;
    public static final UniqueKey<ScenarioCoverageSetRecord> SCENARIO_COVERAGE_SET_SCENARIO_ORDER_KEY = UniqueKeys0.SCENARIO_COVERAGE_SET_SCENARIO_ORDER_KEY;
    public static final UniqueKey<ScenarioDescriptionRecord> SCENARIO_DESCRIPTION_PKEY = UniqueKeys0.SCENARIO_DESCRIPTION_PKEY;
    public static final UniqueKey<TouchstoneRecord> TOUCHSTONE_PKEY = UniqueKeys0.TOUCHSTONE_PKEY;
    public static final UniqueKey<TouchstoneRecord> TOUCHSTONE_TOUCHSTONE_NAME_VERSION_KEY = UniqueKeys0.TOUCHSTONE_TOUCHSTONE_NAME_VERSION_KEY;
    public static final UniqueKey<TouchstoneCountryRecord> TOUCHSTONE_COUNTRY_PKEY = UniqueKeys0.TOUCHSTONE_COUNTRY_PKEY;
    public static final UniqueKey<TouchstoneNameRecord> TOUCHSTONE_NAME_PKEY = UniqueKeys0.TOUCHSTONE_NAME_PKEY;
    public static final UniqueKey<TouchstoneStatusRecord> TOUCHSTONE_STATUS_PKEY = UniqueKeys0.TOUCHSTONE_STATUS_PKEY;
    public static final UniqueKey<UserRoleRecord> USER_ROLE_PKEY = UniqueKeys0.USER_ROLE_PKEY;
    public static final UniqueKey<VaccineRecord> VACCINE_PKEY = UniqueKeys0.VACCINE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BurdenEstimateRecord, BurdenEstimateSetRecord> BURDEN_ESTIMATE__BURDEN_ESTIMATE_BURDEN_ESTIMATE_SET_FKEY = ForeignKeys0.BURDEN_ESTIMATE__BURDEN_ESTIMATE_BURDEN_ESTIMATE_SET_FKEY;
    public static final ForeignKey<BurdenEstimateRecord, CountryRecord> BURDEN_ESTIMATE__BURDEN_ESTIMATE_COUNTRY_FKEY = ForeignKeys0.BURDEN_ESTIMATE__BURDEN_ESTIMATE_COUNTRY_FKEY;
    public static final ForeignKey<BurdenEstimateRecord, OutcomeRecord> BURDEN_ESTIMATE__BURDEN_ESTIMATE_OUTCOME_FKEY = ForeignKeys0.BURDEN_ESTIMATE__BURDEN_ESTIMATE_OUTCOME_FKEY;
    public static final ForeignKey<BurdenEstimateSetRecord, ModelVersionRecord> BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_MODEL_VERSION_FKEY = ForeignKeys0.BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_MODEL_VERSION_FKEY;
    public static final ForeignKey<BurdenEstimateSetRecord, ResponsibilityRecord> BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_RESPONSIBILITY_FKEY = ForeignKeys0.BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_RESPONSIBILITY_FKEY;
    public static final ForeignKey<BurdenEstimateSetRecord, AppUserRecord> BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_UPLOADED_BY_FKEY = ForeignKeys0.BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_UPLOADED_BY_FKEY;
    public static final ForeignKey<CoverageRecord, CoverageSetRecord> COVERAGE__COVERAGE_COVERAGE_SET_FKEY = ForeignKeys0.COVERAGE__COVERAGE_COVERAGE_SET_FKEY;
    public static final ForeignKey<CoverageRecord, CountryRecord> COVERAGE__COVERAGE_COUNTRY_FKEY = ForeignKeys0.COVERAGE__COVERAGE_COUNTRY_FKEY;
    public static final ForeignKey<CoverageSetRecord, TouchstoneRecord> COVERAGE_SET__COVERAGE_SET_TOUCHSTONE_FKEY = ForeignKeys0.COVERAGE_SET__COVERAGE_SET_TOUCHSTONE_FKEY;
    public static final ForeignKey<CoverageSetRecord, VaccineRecord> COVERAGE_SET__COVERAGE_SET_VACCINE_FKEY = ForeignKeys0.COVERAGE_SET__COVERAGE_SET_VACCINE_FKEY;
    public static final ForeignKey<CoverageSetRecord, GaviSupportLevelRecord> COVERAGE_SET__COVERAGE_SET_GAVI_SUPPORT_LEVEL_FKEY = ForeignKeys0.COVERAGE_SET__COVERAGE_SET_GAVI_SUPPORT_LEVEL_FKEY;
    public static final ForeignKey<CoverageSetRecord, ActivityTypeRecord> COVERAGE_SET__COVERAGE_SET_ACTIVITY_TYPE_FKEY = ForeignKeys0.COVERAGE_SET__COVERAGE_SET_ACTIVITY_TYPE_FKEY;
    public static final ForeignKey<ModelRecord, ModellingGroupRecord> MODEL__MODEL_MODELLING_GROUP_FKEY = ForeignKeys0.MODEL__MODEL_MODELLING_GROUP_FKEY;
    public static final ForeignKey<ModelRecord, ModelRecord> MODEL__MODEL_CURRENT_FKEY = ForeignKeys0.MODEL__MODEL_CURRENT_FKEY;
    public static final ForeignKey<ModelVersionRecord, ModelRecord> MODEL_VERSION__MODEL_VERSION_MODEL_FKEY = ForeignKeys0.MODEL_VERSION__MODEL_VERSION_MODEL_FKEY;
    public static final ForeignKey<ModellingGroupRecord, ModellingGroupRecord> MODELLING_GROUP__MODELLING_GROUP_CURRENT_FKEY = ForeignKeys0.MODELLING_GROUP__MODELLING_GROUP_CURRENT_FKEY;
    public static final ForeignKey<ResponsibilityRecord, ResponsibilitySetRecord> RESPONSIBILITY__RESPONSIBILITY_RESPONSIBILITY_SET_FKEY = ForeignKeys0.RESPONSIBILITY__RESPONSIBILITY_RESPONSIBILITY_SET_FKEY;
    public static final ForeignKey<ResponsibilityRecord, ScenarioRecord> RESPONSIBILITY__RESPONSIBILITY_SCENARIO_FKEY = ForeignKeys0.RESPONSIBILITY__RESPONSIBILITY_SCENARIO_FKEY;
    public static final ForeignKey<ResponsibilitySetRecord, ModellingGroupRecord> RESPONSIBILITY_SET__RESPONSIBILITY_SET_MODELLING_GROUP_FKEY = ForeignKeys0.RESPONSIBILITY_SET__RESPONSIBILITY_SET_MODELLING_GROUP_FKEY;
    public static final ForeignKey<ResponsibilitySetRecord, TouchstoneRecord> RESPONSIBILITY_SET__RESPONSIBILITY_SET_TOUCHSTONE_FKEY = ForeignKeys0.RESPONSIBILITY_SET__RESPONSIBILITY_SET_TOUCHSTONE_FKEY;
    public static final ForeignKey<ResponsibilitySetRecord, ResponsibilitySetStatusRecord> RESPONSIBILITY_SET__RESPONSIBILITY_SET_STATUS_FKEY = ForeignKeys0.RESPONSIBILITY_SET__RESPONSIBILITY_SET_STATUS_FKEY;
    public static final ForeignKey<RolePermissionRecord, RoleRecord> ROLE_PERMISSION__ROLE_PERMISSION_ROLE_FKEY = ForeignKeys0.ROLE_PERMISSION__ROLE_PERMISSION_ROLE_FKEY;
    public static final ForeignKey<RolePermissionRecord, PermissionRecord> ROLE_PERMISSION__ROLE_PERMISSION_PERMISSION_FKEY = ForeignKeys0.ROLE_PERMISSION__ROLE_PERMISSION_PERMISSION_FKEY;
    public static final ForeignKey<ScenarioRecord, TouchstoneRecord> SCENARIO__SCENARIO_TOUCHSTONE_FKEY = ForeignKeys0.SCENARIO__SCENARIO_TOUCHSTONE_FKEY;
    public static final ForeignKey<ScenarioRecord, ScenarioDescriptionRecord> SCENARIO__SCENARIO_SCENARIO_DESCRIPTION_FKEY = ForeignKeys0.SCENARIO__SCENARIO_SCENARIO_DESCRIPTION_FKEY;
    public static final ForeignKey<ScenarioCoverageSetRecord, ScenarioRecord> SCENARIO_COVERAGE_SET__SCENARIO_COVERAGE_SET_SCENARIO_FKEY = ForeignKeys0.SCENARIO_COVERAGE_SET__SCENARIO_COVERAGE_SET_SCENARIO_FKEY;
    public static final ForeignKey<ScenarioCoverageSetRecord, CoverageSetRecord> SCENARIO_COVERAGE_SET__SCENARIO_COVERAGE_SET_COVERAGE_SET_FKEY = ForeignKeys0.SCENARIO_COVERAGE_SET__SCENARIO_COVERAGE_SET_COVERAGE_SET_FKEY;
    public static final ForeignKey<ScenarioDescriptionRecord, DiseaseRecord> SCENARIO_DESCRIPTION__SCENARIO_DESCRIPTION_DISEASE_FKEY = ForeignKeys0.SCENARIO_DESCRIPTION__SCENARIO_DESCRIPTION_DISEASE_FKEY;
    public static final ForeignKey<TouchstoneRecord, TouchstoneNameRecord> TOUCHSTONE__TOUCHSTONE_TOUCHSTONE_NAME_FKEY = ForeignKeys0.TOUCHSTONE__TOUCHSTONE_TOUCHSTONE_NAME_FKEY;
    public static final ForeignKey<TouchstoneRecord, TouchstoneStatusRecord> TOUCHSTONE__TOUCHSTONE_STATUS_FKEY = ForeignKeys0.TOUCHSTONE__TOUCHSTONE_STATUS_FKEY;
    public static final ForeignKey<TouchstoneCountryRecord, TouchstoneRecord> TOUCHSTONE_COUNTRY__TOUCHSTONE_COUNTRY_TOUCHSTONE_FKEY = ForeignKeys0.TOUCHSTONE_COUNTRY__TOUCHSTONE_COUNTRY_TOUCHSTONE_FKEY;
    public static final ForeignKey<TouchstoneCountryRecord, CountryRecord> TOUCHSTONE_COUNTRY__TOUCHSTONE_COUNTRY_COUNTRY_FKEY = ForeignKeys0.TOUCHSTONE_COUNTRY__TOUCHSTONE_COUNTRY_COUNTRY_FKEY;
    public static final ForeignKey<UserRoleRecord, AppUserRecord> USER_ROLE__USER_ROLE_USERNAME_FKEY = ForeignKeys0.USER_ROLE__USER_ROLE_USERNAME_FKEY;
    public static final ForeignKey<UserRoleRecord, RoleRecord> USER_ROLE__USER_ROLE_ROLE_FKEY = ForeignKeys0.USER_ROLE__USER_ROLE_ROLE_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BurdenEstimateRecord, Integer> IDENTITY_BURDEN_ESTIMATE = createIdentity(BurdenEstimate.BURDEN_ESTIMATE, BurdenEstimate.BURDEN_ESTIMATE.ID);
        public static Identity<BurdenEstimateSetRecord, Integer> IDENTITY_BURDEN_ESTIMATE_SET = createIdentity(BurdenEstimateSet.BURDEN_ESTIMATE_SET, BurdenEstimateSet.BURDEN_ESTIMATE_SET.ID);
        public static Identity<CoverageRecord, Integer> IDENTITY_COVERAGE = createIdentity(Coverage.COVERAGE, Coverage.COVERAGE.ID);
        public static Identity<CoverageSetRecord, Integer> IDENTITY_COVERAGE_SET = createIdentity(CoverageSet.COVERAGE_SET, CoverageSet.COVERAGE_SET.ID);
        public static Identity<ModelVersionRecord, Integer> IDENTITY_MODEL_VERSION = createIdentity(ModelVersion.MODEL_VERSION, ModelVersion.MODEL_VERSION.ID);
        public static Identity<OutcomeRecord, Integer> IDENTITY_OUTCOME = createIdentity(Outcome.OUTCOME, Outcome.OUTCOME.ID);
        public static Identity<ResponsibilityRecord, Integer> IDENTITY_RESPONSIBILITY = createIdentity(Responsibility.RESPONSIBILITY, Responsibility.RESPONSIBILITY.ID);
        public static Identity<ResponsibilitySetRecord, Integer> IDENTITY_RESPONSIBILITY_SET = createIdentity(ResponsibilitySet.RESPONSIBILITY_SET, ResponsibilitySet.RESPONSIBILITY_SET.ID);
        public static Identity<RoleRecord, Integer> IDENTITY_ROLE = createIdentity(Role.ROLE, Role.ROLE.ID);
        public static Identity<ScenarioRecord, Integer> IDENTITY_SCENARIO = createIdentity(Scenario.SCENARIO, Scenario.SCENARIO.ID);
        public static Identity<ScenarioCoverageSetRecord, Integer> IDENTITY_SCENARIO_COVERAGE_SET = createIdentity(ScenarioCoverageSet.SCENARIO_COVERAGE_SET, ScenarioCoverageSet.SCENARIO_COVERAGE_SET.ID);
        public static Identity<TouchstoneCountryRecord, Integer> IDENTITY_TOUCHSTONE_COUNTRY = createIdentity(TouchstoneCountry.TOUCHSTONE_COUNTRY, TouchstoneCountry.TOUCHSTONE_COUNTRY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ActivityTypeRecord> ACTIVITY_TYPE_PKEY = createUniqueKey(ActivityType.ACTIVITY_TYPE, "activity_type_pkey", ActivityType.ACTIVITY_TYPE.ID);
        public static final UniqueKey<AppUserRecord> APP_USER_PKEY = createUniqueKey(AppUser.APP_USER, "app_user_pkey", AppUser.APP_USER.USERNAME);
        public static final UniqueKey<BurdenEstimateRecord> BURDEN_ESTIMATE_PKEY = createUniqueKey(BurdenEstimate.BURDEN_ESTIMATE, "burden_estimate_pkey", BurdenEstimate.BURDEN_ESTIMATE.ID);
        public static final UniqueKey<BurdenEstimateSetRecord> BURDEN_ESTIMATE_SET_PKEY = createUniqueKey(BurdenEstimateSet.BURDEN_ESTIMATE_SET, "burden_estimate_set_pkey", BurdenEstimateSet.BURDEN_ESTIMATE_SET.ID);
        public static final UniqueKey<CountryRecord> COUNTRY_PKEY = createUniqueKey(Country.COUNTRY, "country_pkey", Country.COUNTRY.ID);
        public static final UniqueKey<CoverageRecord> COVERAGE_PKEY = createUniqueKey(Coverage.COVERAGE, "coverage_pkey", Coverage.COVERAGE.ID);
        public static final UniqueKey<CoverageSetRecord> COVERAGE_SET_PKEY = createUniqueKey(CoverageSet.COVERAGE_SET, "coverage_set_pkey", CoverageSet.COVERAGE_SET.ID);
        public static final UniqueKey<DiseaseRecord> DISEASE_PKEY = createUniqueKey(Disease.DISEASE, "disease_pkey", Disease.DISEASE.ID);
        public static final UniqueKey<GaviSupportLevelRecord> GAVI_SUPPORT_LEVEL_PKEY = createUniqueKey(GaviSupportLevel.GAVI_SUPPORT_LEVEL, "gavi_support_level_pkey", GaviSupportLevel.GAVI_SUPPORT_LEVEL.ID);
        public static final UniqueKey<ModelRecord> MODEL_PKEY = createUniqueKey(Model.MODEL, "model_pkey", Model.MODEL.ID);
        public static final UniqueKey<ModelVersionRecord> MODEL_VERSION_PKEY = createUniqueKey(ModelVersion.MODEL_VERSION, "model_version_pkey", ModelVersion.MODEL_VERSION.ID);
        public static final UniqueKey<ModelVersionRecord> MODEL_VERSION_MODEL_VERSION_KEY = createUniqueKey(ModelVersion.MODEL_VERSION, "model_version_model_version_key", ModelVersion.MODEL_VERSION.MODEL, ModelVersion.MODEL_VERSION.VERSION);
        public static final UniqueKey<ModellingGroupRecord> MODELLING_GROUP_PKEY = createUniqueKey(ModellingGroup.MODELLING_GROUP, "modelling_group_pkey", ModellingGroup.MODELLING_GROUP.ID);
        public static final UniqueKey<OutcomeRecord> OUTCOME_PKEY = createUniqueKey(Outcome.OUTCOME, "outcome_pkey", Outcome.OUTCOME.ID);
        public static final UniqueKey<OutcomeRecord> OUTCOME_CODE_KEY = createUniqueKey(Outcome.OUTCOME, "outcome_code_key", Outcome.OUTCOME.CODE);
        public static final UniqueKey<PermissionRecord> PERMISSION_PKEY = createUniqueKey(Permission.PERMISSION, "permission_pkey", Permission.PERMISSION.NAME);
        public static final UniqueKey<ResponsibilityRecord> RESPONSIBILITY_PKEY = createUniqueKey(Responsibility.RESPONSIBILITY, "responsibility_pkey", Responsibility.RESPONSIBILITY.ID);
        public static final UniqueKey<ResponsibilityRecord> RESPONSIBILITY_RESPONSIBILITY_SET_SCENARIO_KEY = createUniqueKey(Responsibility.RESPONSIBILITY, "responsibility_responsibility_set_scenario_key", Responsibility.RESPONSIBILITY.RESPONSIBILITY_SET, Responsibility.RESPONSIBILITY.SCENARIO);
        public static final UniqueKey<ResponsibilitySetRecord> RESPONSIBILITY_SET_PKEY = createUniqueKey(ResponsibilitySet.RESPONSIBILITY_SET, "responsibility_set_pkey", ResponsibilitySet.RESPONSIBILITY_SET.ID);
        public static final UniqueKey<ResponsibilitySetRecord> RESPONSIBILITY_SET_MODELLING_GROUP_TOUCHSTONE_KEY = createUniqueKey(ResponsibilitySet.RESPONSIBILITY_SET, "responsibility_set_modelling_group_touchstone_key", ResponsibilitySet.RESPONSIBILITY_SET.MODELLING_GROUP, ResponsibilitySet.RESPONSIBILITY_SET.TOUCHSTONE);
        public static final UniqueKey<ResponsibilitySetStatusRecord> RESPONSIBILITY_SET_STATUS_PKEY = createUniqueKey(ResponsibilitySetStatus.RESPONSIBILITY_SET_STATUS, "responsibility_set_status_pkey", ResponsibilitySetStatus.RESPONSIBILITY_SET_STATUS.ID);
        public static final UniqueKey<RoleRecord> ROLE_PKEY = createUniqueKey(Role.ROLE, "role_pkey", Role.ROLE.ID);
        public static final UniqueKey<RolePermissionRecord> ROLE_PERMISSION_PKEY = createUniqueKey(RolePermission.ROLE_PERMISSION, "role_permission_pkey", RolePermission.ROLE_PERMISSION.ROLE, RolePermission.ROLE_PERMISSION.PERMISSION);
        public static final UniqueKey<ScenarioRecord> SCENARIO_PKEY = createUniqueKey(Scenario.SCENARIO, "scenario_pkey", Scenario.SCENARIO.ID);
        public static final UniqueKey<ScenarioRecord> SCENARIO_TOUCHSTONE_SCENARIO_DESCRIPTION_KEY = createUniqueKey(Scenario.SCENARIO, "scenario_touchstone_scenario_description_key", Scenario.SCENARIO.TOUCHSTONE, Scenario.SCENARIO.SCENARIO_DESCRIPTION);
        public static final UniqueKey<ScenarioCoverageSetRecord> SCENARIO_COVERAGE_SET_PKEY = createUniqueKey(ScenarioCoverageSet.SCENARIO_COVERAGE_SET, "scenario_coverage_set_pkey", ScenarioCoverageSet.SCENARIO_COVERAGE_SET.ID);
        public static final UniqueKey<ScenarioCoverageSetRecord> SCENARIO_COVERAGE_SET_SCENARIO_ORDER_KEY = createUniqueKey(ScenarioCoverageSet.SCENARIO_COVERAGE_SET, "scenario_coverage_set_scenario_order_key", ScenarioCoverageSet.SCENARIO_COVERAGE_SET.SCENARIO, ScenarioCoverageSet.SCENARIO_COVERAGE_SET.ORDER);
        public static final UniqueKey<ScenarioDescriptionRecord> SCENARIO_DESCRIPTION_PKEY = createUniqueKey(ScenarioDescription.SCENARIO_DESCRIPTION, "scenario_description_pkey", ScenarioDescription.SCENARIO_DESCRIPTION.ID);
        public static final UniqueKey<TouchstoneRecord> TOUCHSTONE_PKEY = createUniqueKey(Touchstone.TOUCHSTONE, "touchstone_pkey", Touchstone.TOUCHSTONE.ID);
        public static final UniqueKey<TouchstoneRecord> TOUCHSTONE_TOUCHSTONE_NAME_VERSION_KEY = createUniqueKey(Touchstone.TOUCHSTONE, "touchstone_touchstone_name_version_key", Touchstone.TOUCHSTONE.TOUCHSTONE_NAME, Touchstone.TOUCHSTONE.VERSION);
        public static final UniqueKey<TouchstoneCountryRecord> TOUCHSTONE_COUNTRY_PKEY = createUniqueKey(TouchstoneCountry.TOUCHSTONE_COUNTRY, "touchstone_country_pkey", TouchstoneCountry.TOUCHSTONE_COUNTRY.ID);
        public static final UniqueKey<TouchstoneNameRecord> TOUCHSTONE_NAME_PKEY = createUniqueKey(TouchstoneName.TOUCHSTONE_NAME, "touchstone_name_pkey", TouchstoneName.TOUCHSTONE_NAME.ID);
        public static final UniqueKey<TouchstoneStatusRecord> TOUCHSTONE_STATUS_PKEY = createUniqueKey(TouchstoneStatus.TOUCHSTONE_STATUS, "touchstone_status_pkey", TouchstoneStatus.TOUCHSTONE_STATUS.ID);
        public static final UniqueKey<UserRoleRecord> USER_ROLE_PKEY = createUniqueKey(UserRole.USER_ROLE, "user_role_pkey", UserRole.USER_ROLE.USERNAME, UserRole.USER_ROLE.ROLE, UserRole.USER_ROLE.SCOPE_ID);
        public static final UniqueKey<VaccineRecord> VACCINE_PKEY = createUniqueKey(Vaccine.VACCINE, "vaccine_pkey", Vaccine.VACCINE.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BurdenEstimateRecord, BurdenEstimateSetRecord> BURDEN_ESTIMATE__BURDEN_ESTIMATE_BURDEN_ESTIMATE_SET_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.BURDEN_ESTIMATE_SET_PKEY, BurdenEstimate.BURDEN_ESTIMATE, "burden_estimate__burden_estimate_burden_estimate_set_fkey", BurdenEstimate.BURDEN_ESTIMATE.BURDEN_ESTIMATE_SET);
        public static final ForeignKey<BurdenEstimateRecord, CountryRecord> BURDEN_ESTIMATE__BURDEN_ESTIMATE_COUNTRY_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.COUNTRY_PKEY, BurdenEstimate.BURDEN_ESTIMATE, "burden_estimate__burden_estimate_country_fkey", BurdenEstimate.BURDEN_ESTIMATE.COUNTRY);
        public static final ForeignKey<BurdenEstimateRecord, OutcomeRecord> BURDEN_ESTIMATE__BURDEN_ESTIMATE_OUTCOME_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.OUTCOME_PKEY, BurdenEstimate.BURDEN_ESTIMATE, "burden_estimate__burden_estimate_outcome_fkey", BurdenEstimate.BURDEN_ESTIMATE.OUTCOME);
        public static final ForeignKey<BurdenEstimateSetRecord, ModelVersionRecord> BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_MODEL_VERSION_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.MODEL_VERSION_PKEY, BurdenEstimateSet.BURDEN_ESTIMATE_SET, "burden_estimate_set__burden_estimate_set_model_version_fkey", BurdenEstimateSet.BURDEN_ESTIMATE_SET.MODEL_VERSION);
        public static final ForeignKey<BurdenEstimateSetRecord, ResponsibilityRecord> BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_RESPONSIBILITY_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.RESPONSIBILITY_PKEY, BurdenEstimateSet.BURDEN_ESTIMATE_SET, "burden_estimate_set__burden_estimate_set_responsibility_fkey", BurdenEstimateSet.BURDEN_ESTIMATE_SET.RESPONSIBILITY);
        public static final ForeignKey<BurdenEstimateSetRecord, AppUserRecord> BURDEN_ESTIMATE_SET__BURDEN_ESTIMATE_SET_UPLOADED_BY_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.APP_USER_PKEY, BurdenEstimateSet.BURDEN_ESTIMATE_SET, "burden_estimate_set__burden_estimate_set_uploaded_by_fkey", BurdenEstimateSet.BURDEN_ESTIMATE_SET.UPLOADED_BY);
        public static final ForeignKey<CoverageRecord, CoverageSetRecord> COVERAGE__COVERAGE_COVERAGE_SET_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.COVERAGE_SET_PKEY, Coverage.COVERAGE, "coverage__coverage_coverage_set_fkey", Coverage.COVERAGE.COVERAGE_SET);
        public static final ForeignKey<CoverageRecord, CountryRecord> COVERAGE__COVERAGE_COUNTRY_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.COUNTRY_PKEY, Coverage.COVERAGE, "coverage__coverage_country_fkey", Coverage.COVERAGE.COUNTRY);
        public static final ForeignKey<CoverageSetRecord, TouchstoneRecord> COVERAGE_SET__COVERAGE_SET_TOUCHSTONE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.TOUCHSTONE_PKEY, CoverageSet.COVERAGE_SET, "coverage_set__coverage_set_touchstone_fkey", CoverageSet.COVERAGE_SET.TOUCHSTONE);
        public static final ForeignKey<CoverageSetRecord, VaccineRecord> COVERAGE_SET__COVERAGE_SET_VACCINE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.VACCINE_PKEY, CoverageSet.COVERAGE_SET, "coverage_set__coverage_set_vaccine_fkey", CoverageSet.COVERAGE_SET.VACCINE);
        public static final ForeignKey<CoverageSetRecord, GaviSupportLevelRecord> COVERAGE_SET__COVERAGE_SET_GAVI_SUPPORT_LEVEL_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.GAVI_SUPPORT_LEVEL_PKEY, CoverageSet.COVERAGE_SET, "coverage_set__coverage_set_gavi_support_level_fkey", CoverageSet.COVERAGE_SET.GAVI_SUPPORT_LEVEL);
        public static final ForeignKey<CoverageSetRecord, ActivityTypeRecord> COVERAGE_SET__COVERAGE_SET_ACTIVITY_TYPE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.ACTIVITY_TYPE_PKEY, CoverageSet.COVERAGE_SET, "coverage_set__coverage_set_activity_type_fkey", CoverageSet.COVERAGE_SET.ACTIVITY_TYPE);
        public static final ForeignKey<ModelRecord, ModellingGroupRecord> MODEL__MODEL_MODELLING_GROUP_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.MODELLING_GROUP_PKEY, Model.MODEL, "model__model_modelling_group_fkey", Model.MODEL.MODELLING_GROUP);
        public static final ForeignKey<ModelRecord, ModelRecord> MODEL__MODEL_CURRENT_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.MODEL_PKEY, Model.MODEL, "model__model_current_fkey", Model.MODEL.CURRENT);
        public static final ForeignKey<ModelVersionRecord, ModelRecord> MODEL_VERSION__MODEL_VERSION_MODEL_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.MODEL_PKEY, ModelVersion.MODEL_VERSION, "model_version__model_version_model_fkey", ModelVersion.MODEL_VERSION.MODEL);
        public static final ForeignKey<ModellingGroupRecord, ModellingGroupRecord> MODELLING_GROUP__MODELLING_GROUP_CURRENT_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.MODELLING_GROUP_PKEY, ModellingGroup.MODELLING_GROUP, "modelling_group__modelling_group_current_fkey", ModellingGroup.MODELLING_GROUP.CURRENT);
        public static final ForeignKey<ResponsibilityRecord, ResponsibilitySetRecord> RESPONSIBILITY__RESPONSIBILITY_RESPONSIBILITY_SET_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.RESPONSIBILITY_SET_PKEY, Responsibility.RESPONSIBILITY, "responsibility__responsibility_responsibility_set_fkey", Responsibility.RESPONSIBILITY.RESPONSIBILITY_SET);
        public static final ForeignKey<ResponsibilityRecord, ScenarioRecord> RESPONSIBILITY__RESPONSIBILITY_SCENARIO_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.SCENARIO_PKEY, Responsibility.RESPONSIBILITY, "responsibility__responsibility_scenario_fkey", Responsibility.RESPONSIBILITY.SCENARIO);
        public static final ForeignKey<ResponsibilitySetRecord, ModellingGroupRecord> RESPONSIBILITY_SET__RESPONSIBILITY_SET_MODELLING_GROUP_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.MODELLING_GROUP_PKEY, ResponsibilitySet.RESPONSIBILITY_SET, "responsibility_set__responsibility_set_modelling_group_fkey", ResponsibilitySet.RESPONSIBILITY_SET.MODELLING_GROUP);
        public static final ForeignKey<ResponsibilitySetRecord, TouchstoneRecord> RESPONSIBILITY_SET__RESPONSIBILITY_SET_TOUCHSTONE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.TOUCHSTONE_PKEY, ResponsibilitySet.RESPONSIBILITY_SET, "responsibility_set__responsibility_set_touchstone_fkey", ResponsibilitySet.RESPONSIBILITY_SET.TOUCHSTONE);
        public static final ForeignKey<ResponsibilitySetRecord, ResponsibilitySetStatusRecord> RESPONSIBILITY_SET__RESPONSIBILITY_SET_STATUS_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.RESPONSIBILITY_SET_STATUS_PKEY, ResponsibilitySet.RESPONSIBILITY_SET, "responsibility_set__responsibility_set_status_fkey", ResponsibilitySet.RESPONSIBILITY_SET.STATUS);
        public static final ForeignKey<RolePermissionRecord, RoleRecord> ROLE_PERMISSION__ROLE_PERMISSION_ROLE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.ROLE_PKEY, RolePermission.ROLE_PERMISSION, "role_permission__role_permission_role_fkey", RolePermission.ROLE_PERMISSION.ROLE);
        public static final ForeignKey<RolePermissionRecord, PermissionRecord> ROLE_PERMISSION__ROLE_PERMISSION_PERMISSION_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.PERMISSION_PKEY, RolePermission.ROLE_PERMISSION, "role_permission__role_permission_permission_fkey", RolePermission.ROLE_PERMISSION.PERMISSION);
        public static final ForeignKey<ScenarioRecord, TouchstoneRecord> SCENARIO__SCENARIO_TOUCHSTONE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.TOUCHSTONE_PKEY, Scenario.SCENARIO, "scenario__scenario_touchstone_fkey", Scenario.SCENARIO.TOUCHSTONE);
        public static final ForeignKey<ScenarioRecord, ScenarioDescriptionRecord> SCENARIO__SCENARIO_SCENARIO_DESCRIPTION_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.SCENARIO_DESCRIPTION_PKEY, Scenario.SCENARIO, "scenario__scenario_scenario_description_fkey", Scenario.SCENARIO.SCENARIO_DESCRIPTION);
        public static final ForeignKey<ScenarioCoverageSetRecord, ScenarioRecord> SCENARIO_COVERAGE_SET__SCENARIO_COVERAGE_SET_SCENARIO_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.SCENARIO_PKEY, ScenarioCoverageSet.SCENARIO_COVERAGE_SET, "scenario_coverage_set__scenario_coverage_set_scenario_fkey", ScenarioCoverageSet.SCENARIO_COVERAGE_SET.SCENARIO);
        public static final ForeignKey<ScenarioCoverageSetRecord, CoverageSetRecord> SCENARIO_COVERAGE_SET__SCENARIO_COVERAGE_SET_COVERAGE_SET_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.COVERAGE_SET_PKEY, ScenarioCoverageSet.SCENARIO_COVERAGE_SET, "scenario_coverage_set__scenario_coverage_set_coverage_set_fkey", ScenarioCoverageSet.SCENARIO_COVERAGE_SET.COVERAGE_SET);
        public static final ForeignKey<ScenarioDescriptionRecord, DiseaseRecord> SCENARIO_DESCRIPTION__SCENARIO_DESCRIPTION_DISEASE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.DISEASE_PKEY, ScenarioDescription.SCENARIO_DESCRIPTION, "scenario_description__scenario_description_disease_fkey", ScenarioDescription.SCENARIO_DESCRIPTION.DISEASE);
        public static final ForeignKey<TouchstoneRecord, TouchstoneNameRecord> TOUCHSTONE__TOUCHSTONE_TOUCHSTONE_NAME_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.TOUCHSTONE_NAME_PKEY, Touchstone.TOUCHSTONE, "touchstone__touchstone_touchstone_name_fkey", Touchstone.TOUCHSTONE.TOUCHSTONE_NAME);
        public static final ForeignKey<TouchstoneRecord, TouchstoneStatusRecord> TOUCHSTONE__TOUCHSTONE_STATUS_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.TOUCHSTONE_STATUS_PKEY, Touchstone.TOUCHSTONE, "touchstone__touchstone_status_fkey", Touchstone.TOUCHSTONE.STATUS);
        public static final ForeignKey<TouchstoneCountryRecord, TouchstoneRecord> TOUCHSTONE_COUNTRY__TOUCHSTONE_COUNTRY_TOUCHSTONE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.TOUCHSTONE_PKEY, TouchstoneCountry.TOUCHSTONE_COUNTRY, "touchstone_country__touchstone_country_touchstone_fkey", TouchstoneCountry.TOUCHSTONE_COUNTRY.TOUCHSTONE);
        public static final ForeignKey<TouchstoneCountryRecord, CountryRecord> TOUCHSTONE_COUNTRY__TOUCHSTONE_COUNTRY_COUNTRY_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.COUNTRY_PKEY, TouchstoneCountry.TOUCHSTONE_COUNTRY, "touchstone_country__touchstone_country_country_fkey", TouchstoneCountry.TOUCHSTONE_COUNTRY.COUNTRY);
        public static final ForeignKey<UserRoleRecord, AppUserRecord> USER_ROLE__USER_ROLE_USERNAME_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.APP_USER_PKEY, UserRole.USER_ROLE, "user_role__user_role_username_fkey", UserRole.USER_ROLE.USERNAME);
        public static final ForeignKey<UserRoleRecord, RoleRecord> USER_ROLE__USER_ROLE_ROLE_FKEY = createForeignKey(org.vaccineimpact.api.db.Keys.ROLE_PKEY, UserRole.USER_ROLE, "user_role__user_role_role_fkey", UserRole.USER_ROLE.ROLE);
    }
}
