/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.api_access_log_id_seq</code>
     */
    public static final Sequence<Integer> API_ACCESS_LOG_ID_SEQ = new SequenceImpl<Integer>("api_access_log_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.burden_estimate_expectation_id_seq</code>
     */
    public static final Sequence<Integer> BURDEN_ESTIMATE_EXPECTATION_ID_SEQ = new SequenceImpl<Integer>("burden_estimate_expectation_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.burden_estimate_set_id_seq</code>
     */
    public static final Sequence<Integer> BURDEN_ESTIMATE_SET_ID_SEQ = new SequenceImpl<Integer>("burden_estimate_set_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.burden_estimate_set_problem_id_seq</code>
     */
    public static final Sequence<Integer> BURDEN_ESTIMATE_SET_PROBLEM_ID_SEQ = new SequenceImpl<Integer>("burden_estimate_set_problem_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.burden_outcome_id_seq</code>
     */
    public static final Sequence<Integer> BURDEN_OUTCOME_ID_SEQ = new SequenceImpl<Integer>("burden_outcome_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.country_cofinance_id_seq</code>
     */
    public static final Sequence<Integer> COUNTRY_COFINANCE_ID_SEQ = new SequenceImpl<Integer>("country_cofinance_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.country_disease_endemic_id_seq</code>
     */
    public static final Sequence<Integer> COUNTRY_DISEASE_ENDEMIC_ID_SEQ = new SequenceImpl<Integer>("country_disease_endemic_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.country_fragility_id_seq</code>
     */
    public static final Sequence<Integer> COUNTRY_FRAGILITY_ID_SEQ = new SequenceImpl<Integer>("country_fragility_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.country_metadata_id_seq</code>
     */
    public static final Sequence<Integer> COUNTRY_METADATA_ID_SEQ = new SequenceImpl<Integer>("country_metadata_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.country_vaccine_metadata_id_seq</code>
     */
    public static final Sequence<Integer> COUNTRY_VACCINE_METADATA_ID_SEQ = new SequenceImpl<Integer>("country_vaccine_metadata_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.country_worldbank_status_id_seq</code>
     */
    public static final Sequence<Integer> COUNTRY_WORLDBANK_STATUS_ID_SEQ = new SequenceImpl<Integer>("country_worldbank_status_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.coverage_id_seq</code>
     */
    public static final Sequence<Integer> COVERAGE_ID_SEQ = new SequenceImpl<Integer>("coverage_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.coverage_set_id_seq</code>
     */
    public static final Sequence<Integer> COVERAGE_SET_ID_SEQ = new SequenceImpl<Integer>("coverage_set_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.demographic_dataset_id_seq</code>
     */
    public static final Sequence<Integer> DEMOGRAPHIC_DATASET_ID_SEQ = new SequenceImpl<Integer>("demographic_dataset_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.demographic_source_id_seq</code>
     */
    public static final Sequence<Integer> DEMOGRAPHIC_SOURCE_ID_SEQ = new SequenceImpl<Integer>("demographic_source_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.demographic_statistic_id_seq</code>
     */
    public static final Sequence<Integer> DEMOGRAPHIC_STATISTIC_ID_SEQ = new SequenceImpl<Integer>("demographic_statistic_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.demographic_statistic_type_id_seq</code>
     */
    public static final Sequence<Integer> DEMOGRAPHIC_STATISTIC_TYPE_ID_SEQ = new SequenceImpl<Integer>("demographic_statistic_type_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.demographic_value_unit_id_seq</code>
     */
    public static final Sequence<Integer> DEMOGRAPHIC_VALUE_UNIT_ID_SEQ = new SequenceImpl<Integer>("demographic_value_unit_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.demographic_variant_id_seq</code>
     */
    public static final Sequence<Integer> DEMOGRAPHIC_VARIANT_ID_SEQ = new SequenceImpl<Integer>("demographic_variant_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.disability_weight_id_seq</code>
     */
    public static final Sequence<Integer> DISABILITY_WEIGHT_ID_SEQ = new SequenceImpl<Integer>("disability_weight_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.gavi_eligibility_id_seq</code>
     */
    public static final Sequence<Integer> GAVI_ELIGIBILITY_ID_SEQ = new SequenceImpl<Integer>("gavi_eligibility_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.gavi_focal_model_id_seq</code>
     */
    public static final Sequence<Integer> GAVI_FOCAL_MODEL_ID_SEQ = new SequenceImpl<Integer>("gavi_focal_model_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.gender_id_seq</code>
     */
    public static final Sequence<Integer> GENDER_ID_SEQ = new SequenceImpl<Integer>("gender_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.impact_estimate_id_seq</code>
     */
    public static final Sequence<Integer> IMPACT_ESTIMATE_ID_SEQ = new SequenceImpl<Integer>("impact_estimate_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.impact_estimate_ingredient_id_seq</code>
     */
    public static final Sequence<Integer> IMPACT_ESTIMATE_INGREDIENT_ID_SEQ = new SequenceImpl<Integer>("impact_estimate_ingredient_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.impact_estimate_recipe_id_seq</code>
     */
    public static final Sequence<Integer> IMPACT_ESTIMATE_RECIPE_ID_SEQ = new SequenceImpl<Integer>("impact_estimate_recipe_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.impact_estimate_set_id_seq</code>
     */
    public static final Sequence<Integer> IMPACT_ESTIMATE_SET_ID_SEQ = new SequenceImpl<Integer>("impact_estimate_set_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.impact_estimate_set_ingredient_id_seq</code>
     */
    public static final Sequence<Integer> IMPACT_ESTIMATE_SET_INGREDIENT_ID_SEQ = new SequenceImpl<Integer>("impact_estimate_set_ingredient_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.model_run_internal_id_seq</code>
     */
    public static final Sequence<Integer> MODEL_RUN_INTERNAL_ID_SEQ = new SequenceImpl<Integer>("model_run_internal_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.model_run_parameter_id_seq</code>
     */
    public static final Sequence<Integer> MODEL_RUN_PARAMETER_ID_SEQ = new SequenceImpl<Integer>("model_run_parameter_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.model_run_parameter_set_id_seq</code>
     */
    public static final Sequence<Integer> MODEL_RUN_PARAMETER_SET_ID_SEQ = new SequenceImpl<Integer>("model_run_parameter_set_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.model_run_parameter_value_id_seq</code>
     */
    public static final Sequence<Integer> MODEL_RUN_PARAMETER_VALUE_ID_SEQ = new SequenceImpl<Integer>("model_run_parameter_value_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.model_version_id_seq</code>
     */
    public static final Sequence<Integer> MODEL_VERSION_ID_SEQ = new SequenceImpl<Integer>("model_version_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.onetime_token_id_seq</code>
     */
    public static final Sequence<Integer> ONETIME_TOKEN_ID_SEQ = new SequenceImpl<Integer>("onetime_token_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.responsibility_id_seq</code>
     */
    public static final Sequence<Integer> RESPONSIBILITY_ID_SEQ = new SequenceImpl<Integer>("responsibility_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.responsibility_set_id_seq</code>
     */
    public static final Sequence<Integer> RESPONSIBILITY_SET_ID_SEQ = new SequenceImpl<Integer>("responsibility_set_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.role_id_seq</code>
     */
    public static final Sequence<Integer> ROLE_ID_SEQ = new SequenceImpl<Integer>("role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.scenario_coverage_set_id_seq</code>
     */
    public static final Sequence<Integer> SCENARIO_COVERAGE_SET_ID_SEQ = new SequenceImpl<Integer>("scenario_coverage_set_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.scenario_id_seq</code>
     */
    public static final Sequence<Integer> SCENARIO_ID_SEQ = new SequenceImpl<Integer>("scenario_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.touchstone_country_id_seq</code>
     */
    public static final Sequence<Integer> TOUCHSTONE_COUNTRY_ID_SEQ = new SequenceImpl<Integer>("touchstone_country_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.touchstone_demographic_dataset_id_seq</code>
     */
    public static final Sequence<Integer> TOUCHSTONE_DEMOGRAPHIC_DATASET_ID_SEQ = new SequenceImpl<Integer>("touchstone_demographic_dataset_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.touchstone_demographic_source_id_seq</code>
     */
    public static final Sequence<Integer> TOUCHSTONE_DEMOGRAPHIC_SOURCE_ID_SEQ = new SequenceImpl<Integer>("touchstone_demographic_source_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.touchstone_years_id_seq</code>
     */
    public static final Sequence<Integer> TOUCHSTONE_YEARS_ID_SEQ = new SequenceImpl<Integer>("touchstone_years_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.upload_info_id_seq</code>
     */
    public static final Sequence<Integer> UPLOAD_INFO_ID_SEQ = new SequenceImpl<Integer>("upload_info_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.vaccine_routine_age_id_seq</code>
     */
    public static final Sequence<Integer> VACCINE_ROUTINE_AGE_ID_SEQ = new SequenceImpl<Integer>("vaccine_routine_age_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
