/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.api.db;


import org.vaccineimpact.api.db.udt.TablefuncCrosstab_2;
import org.vaccineimpact.api.db.udt.TablefuncCrosstab_3;
import org.vaccineimpact.api.db.udt.TablefuncCrosstab_4;


/**
 * Convenience access to all UDTs in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.tablefunc_crosstab_2</code>
     */
    public static final TablefuncCrosstab_2 TABLEFUNC_CROSSTAB_2 = org.vaccineimpact.api.db.udt.TablefuncCrosstab_2.TABLEFUNC_CROSSTAB_2;

    /**
     * The type <code>public.tablefunc_crosstab_3</code>
     */
    public static final TablefuncCrosstab_3 TABLEFUNC_CROSSTAB_3 = org.vaccineimpact.api.db.udt.TablefuncCrosstab_3.TABLEFUNC_CROSSTAB_3;

    /**
     * The type <code>public.tablefunc_crosstab_4</code>
     */
    public static final TablefuncCrosstab_4 TABLEFUNC_CROSSTAB_4 = org.vaccineimpact.api.db.udt.TablefuncCrosstab_4.TABLEFUNC_CROSSTAB_4;
}
