/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.api.db.tables.BurdenEstimate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BurdenEstimateRecord extends UpdatableRecordImpl<BurdenEstimateRecord> implements Record8<Integer, Integer, Short, Short, Short, Float, Short, Integer> {

    private static final long serialVersionUID = 1194745710;

    /**
     * Setter for <code>public.burden_estimate.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.burden_estimate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.burden_estimate.burden_estimate_set</code>.
     */
    public void setBurdenEstimateSet(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.burden_estimate.burden_estimate_set</code>.
     */
    public Integer getBurdenEstimateSet() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.burden_estimate.country</code>.
     */
    public void setCountry(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.burden_estimate.country</code>.
     */
    public Short getCountry() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.burden_estimate.year</code>.
     */
    public void setYear(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.burden_estimate.year</code>.
     */
    public Short getYear() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.burden_estimate.burden_outcome</code>.
     */
    public void setBurdenOutcome(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.burden_estimate.burden_outcome</code>.
     */
    public Short getBurdenOutcome() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.burden_estimate.value</code>.
     */
    public void setValue(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.burden_estimate.value</code>.
     */
    public Float getValue() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>public.burden_estimate.age</code>.
     */
    public void setAge(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.burden_estimate.age</code>.
     */
    public Short getAge() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.burden_estimate.model_run</code>.
     */
    public void setModelRun(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.burden_estimate.model_run</code>.
     */
    public Integer getModelRun() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Short, Short, Short, Float, Short, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Short, Short, Short, Float, Short, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BurdenEstimate.BURDEN_ESTIMATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return BurdenEstimate.BURDEN_ESTIMATE.BURDEN_ESTIMATE_SET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return BurdenEstimate.BURDEN_ESTIMATE.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return BurdenEstimate.BURDEN_ESTIMATE.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return BurdenEstimate.BURDEN_ESTIMATE.BURDEN_OUTCOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return BurdenEstimate.BURDEN_ESTIMATE.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return BurdenEstimate.BURDEN_ESTIMATE.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return BurdenEstimate.BURDEN_ESTIMATE.MODEL_RUN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getBurdenEstimateSet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component4() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getBurdenOutcome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getModelRun();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBurdenEstimateSet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getBurdenOutcome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getModelRun();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value2(Integer value) {
        setBurdenEstimateSet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value3(Short value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value4(Short value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value5(Short value) {
        setBurdenOutcome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value6(Float value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value7(Short value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord value8(Integer value) {
        setModelRun(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BurdenEstimateRecord values(Integer value1, Integer value2, Short value3, Short value4, Short value5, Float value6, Short value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BurdenEstimateRecord
     */
    public BurdenEstimateRecord() {
        super(BurdenEstimate.BURDEN_ESTIMATE);
    }

    /**
     * Create a detached, initialised BurdenEstimateRecord
     */
    public BurdenEstimateRecord(Integer id, Integer burdenEstimateSet, Short country, Short year, Short burdenOutcome, Float value, Short age, Integer modelRun) {
        super(BurdenEstimate.BURDEN_ESTIMATE);

        set(0, id);
        set(1, burdenEstimateSet);
        set(2, country);
        set(3, year);
        set(4, burdenOutcome);
        set(5, value);
        set(6, age);
        set(7, modelRun);
    }
}
