/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.api.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.api.db.tables.BurdenEstimateSetProblem;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BurdenEstimateSetProblemRecord extends UpdatableRecordImpl<BurdenEstimateSetProblemRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.burden_estimate_set_problem.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set_problem.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.burden_estimate_set_problem.burden_estimate_set</code>.
     */
    public void setBurdenEstimateSet(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.burden_estimate_set_problem.burden_estimate_set</code>.
     */
    public Integer getBurdenEstimateSet() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.burden_estimate_set_problem.problem</code>.
     */
    public void setProblem(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.burden_estimate_set_problem.problem</code>.
     */
    public String getProblem() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BurdenEstimateSetProblem.BURDEN_ESTIMATE_SET_PROBLEM.ID;
    }

    @Override
    public Field<Integer> field2() {
        return BurdenEstimateSetProblem.BURDEN_ESTIMATE_SET_PROBLEM.BURDEN_ESTIMATE_SET;
    }

    @Override
    public Field<String> field3() {
        return BurdenEstimateSetProblem.BURDEN_ESTIMATE_SET_PROBLEM.PROBLEM;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getBurdenEstimateSet();
    }

    @Override
    public String component3() {
        return getProblem();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getBurdenEstimateSet();
    }

    @Override
    public String value3() {
        return getProblem();
    }

    @Override
    public BurdenEstimateSetProblemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BurdenEstimateSetProblemRecord value2(Integer value) {
        setBurdenEstimateSet(value);
        return this;
    }

    @Override
    public BurdenEstimateSetProblemRecord value3(String value) {
        setProblem(value);
        return this;
    }

    @Override
    public BurdenEstimateSetProblemRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BurdenEstimateSetProblemRecord
     */
    public BurdenEstimateSetProblemRecord() {
        super(BurdenEstimateSetProblem.BURDEN_ESTIMATE_SET_PROBLEM);
    }

    /**
     * Create a detached, initialised BurdenEstimateSetProblemRecord
     */
    public BurdenEstimateSetProblemRecord(Integer id, Integer burdenEstimateSet, String problem) {
        super(BurdenEstimateSetProblem.BURDEN_ESTIMATE_SET_PROBLEM);

        setId(id);
        setBurdenEstimateSet(burdenEstimateSet);
        setProblem(problem);
    }
}
