/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.vaccineimpact.api.db.tables.ConfidentialityAgreement;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfidentialityAgreementRecord extends TableRecordImpl<ConfidentialityAgreementRecord> implements Record3<String, Timestamp, Boolean> {

    private static final long serialVersionUID = -2025120685;

    /**
     * Setter for <code>public.confidentiality_agreement.username</code>.
     */
    public void setUsername(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.confidentiality_agreement.username</code>.
     */
    public String getUsername() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.confidentiality_agreement.date</code>.
     */
    public void setDate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.confidentiality_agreement.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.confidentiality_agreement.signed</code>.
     */
    public void setSigned(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.confidentiality_agreement.signed</code>.
     */
    public Boolean getSigned() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Timestamp, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ConfidentialityAgreement.CONFIDENTIALITY_AGREEMENT.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return ConfidentialityAgreement.CONFIDENTIALITY_AGREEMENT.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return ConfidentialityAgreement.CONFIDENTIALITY_AGREEMENT.SIGNED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getSigned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getSigned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfidentialityAgreementRecord value1(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfidentialityAgreementRecord value2(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfidentialityAgreementRecord value3(Boolean value) {
        setSigned(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ConfidentialityAgreementRecord values(String value1, Timestamp value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfidentialityAgreementRecord
     */
    public ConfidentialityAgreementRecord() {
        super(ConfidentialityAgreement.CONFIDENTIALITY_AGREEMENT);
    }

    /**
     * Create a detached, initialised ConfidentialityAgreementRecord
     */
    public ConfidentialityAgreementRecord(String username, Timestamp date, Boolean signed) {
        super(ConfidentialityAgreement.CONFIDENTIALITY_AGREEMENT);

        set(0, username);
        set(1, date);
        set(2, signed);
    }
}
