/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.api.db.tables.DemographicStatisticType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DemographicStatisticTypeRecord extends UpdatableRecordImpl<DemographicStatisticTypeRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = -965381088;

    /**
     * Setter for <code>public.demographic_statistic_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.demographic_statistic_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.demographic_statistic_type.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.demographic_statistic_type.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.demographic_statistic_type.age_interpretation</code>.
     */
    public void setAgeInterpretation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.demographic_statistic_type.age_interpretation</code>.
     */
    public String getAgeInterpretation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.demographic_statistic_type.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.demographic_statistic_type.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DemographicStatisticType.DEMOGRAPHIC_STATISTIC_TYPE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DemographicStatisticType.DEMOGRAPHIC_STATISTIC_TYPE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DemographicStatisticType.DEMOGRAPHIC_STATISTIC_TYPE.AGE_INTERPRETATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DemographicStatisticType.DEMOGRAPHIC_STATISTIC_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAgeInterpretation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicStatisticTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicStatisticTypeRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicStatisticTypeRecord value3(String value) {
        setAgeInterpretation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicStatisticTypeRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DemographicStatisticTypeRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DemographicStatisticTypeRecord
     */
    public DemographicStatisticTypeRecord() {
        super(DemographicStatisticType.DEMOGRAPHIC_STATISTIC_TYPE);
    }

    /**
     * Create a detached, initialised DemographicStatisticTypeRecord
     */
    public DemographicStatisticTypeRecord(Integer id, String code, String ageInterpretation, String name) {
        super(DemographicStatisticType.DEMOGRAPHIC_STATISTIC_TYPE);

        set(0, id);
        set(1, code);
        set(2, ageInterpretation);
        set(3, name);
    }
}
