/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.vaccineimpact.api.db.tables.DisabilityWeight;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisabilityWeightRecord extends UpdatableRecordImpl<DisabilityWeightRecord> implements Record7<Integer, String, String, String, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1806089483;

    /**
     * Setter for <code>public.disability_weight.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.disability_weight.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.disability_weight.touchstone</code>.
     */
    public void setTouchstone(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.disability_weight.touchstone</code>.
     */
    public String getTouchstone() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.disability_weight.disease</code>.
     */
    public void setDisease(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.disability_weight.disease</code>.
     */
    public String getDisease() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.disability_weight.sequela</code>.
     */
    public void setSequela(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.disability_weight.sequela</code>.
     */
    public String getSequela() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.disability_weight.disability_weight</code>.
     */
    public void setDisabilityWeight(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.disability_weight.disability_weight</code>.
     */
    public BigDecimal getDisabilityWeight() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.disability_weight.disability_weight_min</code>.
     */
    public void setDisabilityWeightMin(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.disability_weight.disability_weight_min</code>.
     */
    public BigDecimal getDisabilityWeightMin() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.disability_weight.disability_weight_max</code>.
     */
    public void setDisabilityWeightMax(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.disability_weight.disability_weight_max</code>.
     */
    public BigDecimal getDisabilityWeightMax() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DisabilityWeight.DISABILITY_WEIGHT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DisabilityWeight.DISABILITY_WEIGHT.TOUCHSTONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DisabilityWeight.DISABILITY_WEIGHT.DISEASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DisabilityWeight.DISABILITY_WEIGHT.SEQUELA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return DisabilityWeight.DISABILITY_WEIGHT.DISABILITY_WEIGHT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return DisabilityWeight.DISABILITY_WEIGHT.DISABILITY_WEIGHT_MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return DisabilityWeight.DISABILITY_WEIGHT.DISABILITY_WEIGHT_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTouchstone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDisease();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSequela();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getDisabilityWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getDisabilityWeightMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getDisabilityWeightMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTouchstone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisease();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSequela();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getDisabilityWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getDisabilityWeightMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getDisabilityWeightMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value2(String value) {
        setTouchstone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value3(String value) {
        setDisease(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value4(String value) {
        setSequela(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value5(BigDecimal value) {
        setDisabilityWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value6(BigDecimal value) {
        setDisabilityWeightMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord value7(BigDecimal value) {
        setDisabilityWeightMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DisabilityWeightRecord values(Integer value1, String value2, String value3, String value4, BigDecimal value5, BigDecimal value6, BigDecimal value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DisabilityWeightRecord
     */
    public DisabilityWeightRecord() {
        super(DisabilityWeight.DISABILITY_WEIGHT);
    }

    /**
     * Create a detached, initialised DisabilityWeightRecord
     */
    public DisabilityWeightRecord(Integer id, String touchstone, String disease, String sequela, BigDecimal disabilityWeight, BigDecimal disabilityWeightMin, BigDecimal disabilityWeightMax) {
        super(DisabilityWeight.DISABILITY_WEIGHT);

        set(0, id);
        set(1, touchstone);
        set(2, disease);
        set(3, sequela);
        set(4, disabilityWeight);
        set(5, disabilityWeightMin);
        set(6, disabilityWeightMax);
    }
}
