/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;
import org.vaccineimpact.api.db.tables.NormalRand;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NormalRandRecord extends TableRecordImpl<NormalRandRecord> implements Record1<Double> {

    private static final long serialVersionUID = -1345101385;

    /**
     * Setter for <code>public.normal_rand.normal_rand</code>.
     */
    public void setNormalRand(Double value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.normal_rand.normal_rand</code>.
     */
    public Double getNormalRand() {
        return (Double) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Double> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Double> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field1() {
        return NormalRand.NORMAL_RAND.NORMAL_RAND_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component1() {
        return getNormalRand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value1() {
        return getNormalRand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormalRandRecord value1(Double value) {
        setNormalRand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NormalRandRecord values(Double value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NormalRandRecord
     */
    public NormalRandRecord() {
        super(NormalRand.NORMAL_RAND);
    }

    /**
     * Create a detached, initialised NormalRandRecord
     */
    public NormalRandRecord(Double normalRand) {
        super(NormalRand.NORMAL_RAND);

        set(0, normalRand);
    }
}
