/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.api.db.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.vaccineimpact.api.db.tables.SelectBurdenData1;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectBurdenData1Record extends TableRecordImpl<SelectBurdenData1Record> implements Record3<String, Integer, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.select_burden_data1.country</code>.
     */
    public void setCountry(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.select_burden_data1.country</code>.
     */
    public String getCountry() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.select_burden_data1.year</code>.
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.select_burden_data1.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.select_burden_data1.value1</code>.
     */
    public void setValue1(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.select_burden_data1.value1</code>.
     */
    public BigDecimal getValue1() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Integer, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SelectBurdenData1.SELECT_BURDEN_DATA1.COUNTRY;
    }

    @Override
    public Field<Integer> field2() {
        return SelectBurdenData1.SELECT_BURDEN_DATA1.YEAR;
    }

    @Override
    public Field<BigDecimal> field3() {
        return SelectBurdenData1.SELECT_BURDEN_DATA1.VALUE1;
    }

    @Override
    public String component1() {
        return getCountry();
    }

    @Override
    public Integer component2() {
        return getYear();
    }

    @Override
    public BigDecimal component3() {
        return getValue1();
    }

    @Override
    public String value1() {
        return getCountry();
    }

    @Override
    public Integer value2() {
        return getYear();
    }

    @Override
    public BigDecimal value3() {
        return getValue1();
    }

    @Override
    public SelectBurdenData1Record value1(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public SelectBurdenData1Record value2(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public SelectBurdenData1Record value3(BigDecimal value) {
        setValue1(value);
        return this;
    }

    @Override
    public SelectBurdenData1Record values(String value1, Integer value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectBurdenData1Record
     */
    public SelectBurdenData1Record() {
        super(SelectBurdenData1.SELECT_BURDEN_DATA1);
    }

    /**
     * Create a detached, initialised SelectBurdenData1Record
     */
    public SelectBurdenData1Record(String country, Integer year, BigDecimal value1) {
        super(SelectBurdenData1.SELECT_BURDEN_DATA1);

        setCountry(country);
        setYear(year);
        setValue1(value1);
    }
}
