/*
 * This file is generated by jOOQ.
 */
package org.vaccineimpact.api.db.tables;


import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.api.db.Keys;
import org.vaccineimpact.api.db.Public;
import org.vaccineimpact.api.db.tables.records.CofinanceStatusRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CofinanceStatus extends TableImpl<CofinanceStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cofinance_status</code>
     */
    public static final CofinanceStatus COFINANCE_STATUS = new CofinanceStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CofinanceStatusRecord> getRecordType() {
        return CofinanceStatusRecord.class;
    }

    /**
     * The column <code>public.cofinance_status.id</code>.
     */
    public final TableField<CofinanceStatusRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.cofinance_status.name</code>.
     */
    public final TableField<CofinanceStatusRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private CofinanceStatus(Name alias, Table<CofinanceStatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private CofinanceStatus(Name alias, Table<CofinanceStatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.cofinance_status</code> table reference
     */
    public CofinanceStatus(String alias) {
        this(DSL.name(alias), COFINANCE_STATUS);
    }

    /**
     * Create an aliased <code>public.cofinance_status</code> table reference
     */
    public CofinanceStatus(Name alias) {
        this(alias, COFINANCE_STATUS);
    }

    /**
     * Create a <code>public.cofinance_status</code> table reference
     */
    public CofinanceStatus() {
        this(DSL.name("cofinance_status"), null);
    }

    public <O extends Record> CofinanceStatus(Table<O> child, ForeignKey<O, CofinanceStatusRecord> key) {
        super(child, key, COFINANCE_STATUS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CofinanceStatusRecord> getPrimaryKey() {
        return Keys.COFINANCE_STATUS_PKEY;
    }

    @Override
    public CofinanceStatus as(String alias) {
        return new CofinanceStatus(DSL.name(alias), this);
    }

    @Override
    public CofinanceStatus as(Name alias) {
        return new CofinanceStatus(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CofinanceStatus rename(String name) {
        return new CofinanceStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CofinanceStatus rename(Name name) {
        return new CofinanceStatus(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
