/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.api.db.Indexes;
import org.vaccineimpact.api.db.Keys;
import org.vaccineimpact.api.db.Public;
import org.vaccineimpact.api.db.tables.records.CoverageSetRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoverageSet extends TableImpl<CoverageSetRecord> {

    private static final long serialVersionUID = -1896776201;

    /**
     * The reference instance of <code>public.coverage_set</code>
     */
    public static final CoverageSet COVERAGE_SET = new CoverageSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoverageSetRecord> getRecordType() {
        return CoverageSetRecord.class;
    }

    /**
     * The column <code>public.coverage_set.id</code>.
     */
    public final TableField<CoverageSetRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('coverage_set_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.coverage_set.name</code>.
     */
    public final TableField<CoverageSetRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.coverage_set.touchstone</code>.
     */
    public final TableField<CoverageSetRecord, String> TOUCHSTONE = createField("touchstone", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.coverage_set.vaccine</code>.
     */
    public final TableField<CoverageSetRecord, String> VACCINE = createField("vaccine", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.coverage_set.gavi_support_level</code>.
     */
    public final TableField<CoverageSetRecord, String> GAVI_SUPPORT_LEVEL = createField("gavi_support_level", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.coverage_set.activity_type</code>.
     */
    public final TableField<CoverageSetRecord, String> ACTIVITY_TYPE = createField("activity_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.coverage_set</code> table reference
     */
    public CoverageSet() {
        this(DSL.name("coverage_set"), null);
    }

    /**
     * Create an aliased <code>public.coverage_set</code> table reference
     */
    public CoverageSet(String alias) {
        this(DSL.name(alias), COVERAGE_SET);
    }

    /**
     * Create an aliased <code>public.coverage_set</code> table reference
     */
    public CoverageSet(Name alias) {
        this(alias, COVERAGE_SET);
    }

    private CoverageSet(Name alias, Table<CoverageSetRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoverageSet(Name alias, Table<CoverageSetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.COVERAGE_SET_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CoverageSetRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COVERAGE_SET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CoverageSetRecord> getPrimaryKey() {
        return Keys.COVERAGE_SET_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CoverageSetRecord>> getKeys() {
        return Arrays.<UniqueKey<CoverageSetRecord>>asList(Keys.COVERAGE_SET_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CoverageSetRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CoverageSetRecord, ?>>asList(Keys.COVERAGE_SET__COVERAGE_SET_TOUCHSTONE_FKEY, Keys.COVERAGE_SET__COVERAGE_SET_VACCINE_FKEY, Keys.COVERAGE_SET__COVERAGE_SET_GAVI_SUPPORT_LEVEL_FKEY, Keys.COVERAGE_SET__COVERAGE_SET_ACTIVITY_TYPE_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageSet as(String alias) {
        return new CoverageSet(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoverageSet as(Name alias) {
        return new CoverageSet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoverageSet rename(String name) {
        return new CoverageSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoverageSet rename(Name name) {
        return new CoverageSet(name, null);
    }
}
