/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.api.db.Public;
import org.vaccineimpact.api.db.tables.records.Crosstab2Record;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crosstab2 extends TableImpl<Crosstab2Record> {

    private static final long serialVersionUID = -1959876107;

    /**
     * The reference instance of <code>public.crosstab2</code>
     */
    public static final Crosstab2 CROSSTAB2 = new Crosstab2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Crosstab2Record> getRecordType() {
        return Crosstab2Record.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<Crosstab2Record, Object> CROSSTAB2_ = createField("crosstab2", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), this, "");

    /**
     * Create a <code>public.crosstab2</code> table reference
     */
    public Crosstab2() {
        this(DSL.name("crosstab2"), null);
    }

    /**
     * Create an aliased <code>public.crosstab2</code> table reference
     */
    public Crosstab2(String alias) {
        this(DSL.name(alias), CROSSTAB2);
    }

    /**
     * Create an aliased <code>public.crosstab2</code> table reference
     */
    public Crosstab2(Name alias) {
        this(alias, CROSSTAB2);
    }

    private Crosstab2(Name alias, Table<Crosstab2Record> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private Crosstab2(Name alias, Table<Crosstab2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crosstab2 as(String alias) {
        return new Crosstab2(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crosstab2 as(Name alias) {
        return new Crosstab2(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public Crosstab2 rename(String name) {
        return new Crosstab2(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public Crosstab2 rename(Name name) {
        return new Crosstab2(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public Crosstab2 call(String __1) {
        return new Crosstab2(DSL.name(getName()), null, new Field[] { 
              DSL.val(__1, org.jooq.impl.SQLDataType.CLOB)
        });
    }

    /**
     * Call this table-valued function
     */
    public Crosstab2 call(Field<String> __1) {
        return new Crosstab2(DSL.name(getName()), null, new Field[] { 
              __1
        });
    }
}
