/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.api.db.Public;
import org.vaccineimpact.api.db.tables.records.CrosstabRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crosstab extends TableImpl<CrosstabRecord> {

    private static final long serialVersionUID = -1463074068;

    /**
     * The reference instance of <code>public.crosstab</code>
     */
    public static final Crosstab CROSSTAB = new Crosstab();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrosstabRecord> getRecordType() {
        return CrosstabRecord.class;
    }

    /**
     * The column <code>public.crosstab.crosstab</code>.
     */
    public final TableField<CrosstabRecord, Record> CROSSTAB_ = createField("crosstab", org.jooq.impl.SQLDataType.RECORD, this, "");

    /**
     * Create a <code>public.crosstab</code> table reference
     */
    public Crosstab() {
        this(DSL.name("crosstab"), null);
    }

    /**
     * Create an aliased <code>public.crosstab</code> table reference
     */
    public Crosstab(String alias) {
        this(DSL.name(alias), CROSSTAB);
    }

    /**
     * Create an aliased <code>public.crosstab</code> table reference
     */
    public Crosstab(Name alias) {
        this(alias, CROSSTAB);
    }

    private Crosstab(Name alias, Table<CrosstabRecord> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private Crosstab(Name alias, Table<CrosstabRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crosstab as(String alias) {
        return new Crosstab(DSL.name(alias), this, parameters);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Crosstab as(Name alias) {
        return new Crosstab(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public Crosstab rename(String name) {
        return new Crosstab(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public Crosstab rename(Name name) {
        return new Crosstab(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public Crosstab call(String __1) {
        return new Crosstab(DSL.name(getName()), null, new Field[] { 
              DSL.val(__1, org.jooq.impl.SQLDataType.CLOB)
        });
    }

    /**
     * Call this table-valued function
     */
    public Crosstab call(Field<String> __1) {
        return new Crosstab(DSL.name(getName()), null, new Field[] { 
              __1
        });
    }
}
