/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.vaccineimpact.api.db.Public;
import org.vaccineimpact.api.db.tables.records.VResponsibilityInfoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VResponsibilityInfo extends TableImpl<VResponsibilityInfoRecord> {

    private static final long serialVersionUID = -96159036;

    /**
     * The reference instance of <code>public.v_responsibility_info</code>
     */
    public static final VResponsibilityInfo V_RESPONSIBILITY_INFO = new VResponsibilityInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VResponsibilityInfoRecord> getRecordType() {
        return VResponsibilityInfoRecord.class;
    }

    /**
     * The column <code>public.v_responsibility_info.touchstone</code>.
     */
    public final TableField<VResponsibilityInfoRecord, String> TOUCHSTONE = createField("touchstone", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_responsibility_info.status</code>.
     */
    public final TableField<VResponsibilityInfoRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_responsibility_info.scenario_description</code>.
     */
    public final TableField<VResponsibilityInfoRecord, String> SCENARIO_DESCRIPTION = createField("scenario_description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_responsibility_info.disease</code>.
     */
    public final TableField<VResponsibilityInfoRecord, String> DISEASE = createField("disease", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.v_responsibility_info.responsibility_id</code>.
     */
    public final TableField<VResponsibilityInfoRecord, Integer> RESPONSIBILITY_ID = createField("responsibility_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.v_responsibility_info.current_burden_estimate_set</code>.
     */
    public final TableField<VResponsibilityInfoRecord, Integer> CURRENT_BURDEN_ESTIMATE_SET = createField("current_burden_estimate_set", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.v_responsibility_info</code> table reference
     */
    public VResponsibilityInfo() {
        this(DSL.name("v_responsibility_info"), null);
    }

    /**
     * Create an aliased <code>public.v_responsibility_info</code> table reference
     */
    public VResponsibilityInfo(String alias) {
        this(DSL.name(alias), V_RESPONSIBILITY_INFO);
    }

    /**
     * Create an aliased <code>public.v_responsibility_info</code> table reference
     */
    public VResponsibilityInfo(Name alias) {
        this(alias, V_RESPONSIBILITY_INFO);
    }

    private VResponsibilityInfo(Name alias, Table<VResponsibilityInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private VResponsibilityInfo(Name alias, Table<VResponsibilityInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VResponsibilityInfo as(String alias) {
        return new VResponsibilityInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VResponsibilityInfo as(Name alias) {
        return new VResponsibilityInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VResponsibilityInfo rename(String name) {
        return new VResponsibilityInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VResponsibilityInfo rename(Name name) {
        return new VResponsibilityInfo(name, null);
    }
}
