broker: pyamqp://guest@montagu_mq_1//
backend: rpc://
servers:
  montagu:
    url: http://montagu_api_1:8080
    user: task.user@example.com
    password: password
  orderlyweb:
    url: http://montagu_orderly_web_1:8888
  smtp:
    host: localhost
    port: 1025
    user:
    password:
    from: noreply@example.com
tasks:
  diagnostic_reports:
    poll_seconds: 5
    reports:
      testGroup:
        testDisease:
          - report_name: minimal
            success_email:
              recipients:
                - minimal_modeller@example.com
                - science@example.com
              subject: "New version of Orderly report"
