/*
 * This file is generated by jOOQ.
*/
package org.vaccineimpact.api.db;


import javax.annotation.Generated;

import org.vaccineimpact.api.db.tables.BurdenEstimate;
import org.vaccineimpact.api.db.tables.BurdenEstimateSet;
import org.vaccineimpact.api.db.tables.Country;
import org.vaccineimpact.api.db.tables.Coverage;
import org.vaccineimpact.api.db.tables.CoverageSet;
import org.vaccineimpact.api.db.tables.Disease;
import org.vaccineimpact.api.db.tables.Model;
import org.vaccineimpact.api.db.tables.ModelVersion;
import org.vaccineimpact.api.db.tables.ModellingGroup;
import org.vaccineimpact.api.db.tables.Outcome;
import org.vaccineimpact.api.db.tables.Permission;
import org.vaccineimpact.api.db.tables.Responsibility;
import org.vaccineimpact.api.db.tables.ResponsibilitySet;
import org.vaccineimpact.api.db.tables.ResponsibilitySetStatus;
import org.vaccineimpact.api.db.tables.Role;
import org.vaccineimpact.api.db.tables.RolePermission;
import org.vaccineimpact.api.db.tables.Scenario;
import org.vaccineimpact.api.db.tables.ScenarioCoverageSet;
import org.vaccineimpact.api.db.tables.ScenarioDescription;
import org.vaccineimpact.api.db.tables.ScenarioType;
import org.vaccineimpact.api.db.tables.Touchstone;
import org.vaccineimpact.api.db.tables.TouchstoneCountry;
import org.vaccineimpact.api.db.tables.TouchstoneStatus;
import org.vaccineimpact.api.db.tables.User;
import org.vaccineimpact.api.db.tables.UserRole;
import org.vaccineimpact.api.db.tables.VaccinationLevel;
import org.vaccineimpact.api.db.tables.Vaccine;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The type <code>public.burden_estimate</code>.
     */
    public static final BurdenEstimate BURDEN_ESTIMATE = org.vaccineimpact.api.db.tables.BurdenEstimate.BURDEN_ESTIMATE;

    /**
     * The type <code>public.burden_estimate_set</code>.
     */
    public static final BurdenEstimateSet BURDEN_ESTIMATE_SET = org.vaccineimpact.api.db.tables.BurdenEstimateSet.BURDEN_ESTIMATE_SET;

    /**
     * The type <code>public.country</code>.
     */
    public static final Country COUNTRY = org.vaccineimpact.api.db.tables.Country.COUNTRY;

    /**
     * The type <code>public.coverage</code>.
     */
    public static final Coverage COVERAGE = org.vaccineimpact.api.db.tables.Coverage.COVERAGE;

    /**
     * The type <code>public.coverage_set</code>.
     */
    public static final CoverageSet COVERAGE_SET = org.vaccineimpact.api.db.tables.CoverageSet.COVERAGE_SET;

    /**
     * The type <code>public.disease</code>.
     */
    public static final Disease DISEASE = org.vaccineimpact.api.db.tables.Disease.DISEASE;

    /**
     * The type <code>public.model</code>.
     */
    public static final Model MODEL = org.vaccineimpact.api.db.tables.Model.MODEL;

    /**
     * The type <code>public.model_version</code>.
     */
    public static final ModelVersion MODEL_VERSION = org.vaccineimpact.api.db.tables.ModelVersion.MODEL_VERSION;

    /**
     * The type <code>public.modelling_group</code>.
     */
    public static final ModellingGroup MODELLING_GROUP = org.vaccineimpact.api.db.tables.ModellingGroup.MODELLING_GROUP;

    /**
     * The type <code>public.outcome</code>.
     */
    public static final Outcome OUTCOME = org.vaccineimpact.api.db.tables.Outcome.OUTCOME;

    /**
     * The type <code>public.permission</code>.
     */
    public static final Permission PERMISSION = org.vaccineimpact.api.db.tables.Permission.PERMISSION;

    /**
     * The type <code>public.responsibility</code>.
     */
    public static final Responsibility RESPONSIBILITY = org.vaccineimpact.api.db.tables.Responsibility.RESPONSIBILITY;

    /**
     * The type <code>public.responsibility_set</code>.
     */
    public static final ResponsibilitySet RESPONSIBILITY_SET = org.vaccineimpact.api.db.tables.ResponsibilitySet.RESPONSIBILITY_SET;

    /**
     * Possible values {incomplete, submitted, approved}
     */
    public static final ResponsibilitySetStatus RESPONSIBILITY_SET_STATUS = org.vaccineimpact.api.db.tables.ResponsibilitySetStatus.RESPONSIBILITY_SET_STATUS;

    /**
     * The type <code>public.role</code>.
     */
    public static final Role ROLE = org.vaccineimpact.api.db.tables.Role.ROLE;

    /**
     * The type <code>public.role_permission</code>.
     */
    public static final RolePermission ROLE_PERMISSION = org.vaccineimpact.api.db.tables.RolePermission.ROLE_PERMISSION;

    /**
     * The type <code>public.scenario</code>.
     */
    public static final Scenario SCENARIO = org.vaccineimpact.api.db.tables.Scenario.SCENARIO;

    /**
     * The type <code>public.scenario_coverage_set</code>.
     */
    public static final ScenarioCoverageSet SCENARIO_COVERAGE_SET = org.vaccineimpact.api.db.tables.ScenarioCoverageSet.SCENARIO_COVERAGE_SET;

    /**
     * The type <code>public.scenario_description</code>.
     */
    public static final ScenarioDescription SCENARIO_DESCRIPTION = org.vaccineimpact.api.db.tables.ScenarioDescription.SCENARIO_DESCRIPTION;

    /**
     * This is just "routine" or "campaign".
     */
    public static final ScenarioType SCENARIO_TYPE = org.vaccineimpact.api.db.tables.ScenarioType.SCENARIO_TYPE;

    /**
     * This is the top-level categorization. It refers to an Operational Forecast from GAVI, a WUENIC July update, or some other data set against which impact estimates are going to be done 
     */
    public static final Touchstone TOUCHSTONE = org.vaccineimpact.api.db.tables.Touchstone.TOUCHSTONE;

    /**
     * The type <code>public.touchstone_country</code>.
     */
    public static final TouchstoneCountry TOUCHSTONE_COUNTRY = org.vaccineimpact.api.db.tables.TouchstoneCountry.TOUCHSTONE_COUNTRY;

    /**
     * Valid values: {in-preparation, open, finished}
     */
    public static final TouchstoneStatus TOUCHSTONE_STATUS = org.vaccineimpact.api.db.tables.TouchstoneStatus.TOUCHSTONE_STATUS;

    /**
     * The type <code>public.user</code>.
     */
    public static final User USER = org.vaccineimpact.api.db.tables.User.USER;

    /**
     * The type <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = org.vaccineimpact.api.db.tables.UserRole.USER_ROLE;

    /**
     * Enum type. Possible values: No vaccination, Vaccination without GAVI support, Vaccination with GAVI support
     */
    public static final VaccinationLevel VACCINATION_LEVEL = org.vaccineimpact.api.db.tables.VaccinationLevel.VACCINATION_LEVEL;

    /**
     * The type <code>public.vaccine</code>.
     */
    public static final Vaccine VACCINE = org.vaccineimpact.api.db.tables.Vaccine.VACCINE;
}
